//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/org/bouncycastle/pqc/crypto/xmss/XMSSReducedSignature.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/NullPointerException.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"
#include "org/bouncycastle/pqc/crypto/xmss/WOTSPlus.h"
#include "org/bouncycastle/pqc/crypto/xmss/WOTSPlusParameters.h"
#include "org/bouncycastle/pqc/crypto/xmss/WOTSPlusSignature.h"
#include "org/bouncycastle/pqc/crypto/xmss/XMSSNode.h"
#include "org/bouncycastle/pqc/crypto/xmss/XMSSParameters.h"
#include "org/bouncycastle/pqc/crypto/xmss/XMSSReducedSignature.h"
#include "org/bouncycastle/pqc/crypto/xmss/XMSSUtil.h"

#if !__has_feature(objc_arc)
#error "org/bouncycastle/pqc/crypto/xmss/XMSSReducedSignature must be compiled with ARC (-fobjc-arc)"
#endif

@interface OrgBouncycastlePqcCryptoXmssXMSSReducedSignature () {
 @public
  OrgBouncycastlePqcCryptoXmssXMSSParameters *params_;
  OrgBouncycastlePqcCryptoXmssWOTSPlusSignature *wotsPlusSignature_;
  id<JavaUtilList> authPath_;
}

@end

J2OBJC_FIELD_SETTER(OrgBouncycastlePqcCryptoXmssXMSSReducedSignature, params_, OrgBouncycastlePqcCryptoXmssXMSSParameters *)
J2OBJC_FIELD_SETTER(OrgBouncycastlePqcCryptoXmssXMSSReducedSignature, wotsPlusSignature_, OrgBouncycastlePqcCryptoXmssWOTSPlusSignature *)
J2OBJC_FIELD_SETTER(OrgBouncycastlePqcCryptoXmssXMSSReducedSignature, authPath_, id<JavaUtilList>)

@interface OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder () {
 @public
  OrgBouncycastlePqcCryptoXmssXMSSParameters *params_;
  OrgBouncycastlePqcCryptoXmssWOTSPlusSignature *wotsPlusSignature_;
  id<JavaUtilList> authPath_;
  IOSByteArray *reducedSignature_;
}

@end

J2OBJC_FIELD_SETTER(OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder, params_, OrgBouncycastlePqcCryptoXmssXMSSParameters *)
J2OBJC_FIELD_SETTER(OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder, wotsPlusSignature_, OrgBouncycastlePqcCryptoXmssWOTSPlusSignature *)
J2OBJC_FIELD_SETTER(OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder, authPath_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder, reducedSignature_, IOSByteArray *)

#line 1 "/Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/org/bouncycastle/pqc/crypto/xmss/XMSSReducedSignature.java"


#line 9
@implementation OrgBouncycastlePqcCryptoXmssXMSSReducedSignature


#line 17
- (instancetype)initWithOrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder:(OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder *)builder {
  OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_initWithOrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder_(self, builder);
  return self;
}


#line 122
- (IOSByteArray *)toByteArray {
  
#line 126
  jint n = [((OrgBouncycastlePqcCryptoXmssXMSSParameters *) nil_chk(params_)) getTreeDigestSize];
  jint signatureSize = [((OrgBouncycastlePqcCryptoXmssWOTSPlusParameters *) nil_chk([((OrgBouncycastlePqcCryptoXmssWOTSPlus *) nil_chk([params_ getWOTSPlus])) getParams])) getLen] * n;
  jint authPathSize = [params_ getHeight] * n;
  jint totalSize = signatureSize + authPathSize;
  IOSByteArray *out = [IOSByteArray newArrayWithLength:totalSize];
  jint position = 0;
  
#line 133
  IOSObjectArray *signature = [((OrgBouncycastlePqcCryptoXmssWOTSPlusSignature *) nil_chk(wotsPlusSignature_)) toByteArray];
  {
    IOSObjectArray *a__ =
#line 134
    signature;
    IOSByteArray * const *b__ = ((IOSObjectArray *) nil_chk(a__))->buffer_;
    IOSByteArray * const *e__ = b__ + a__->size_;
    while (b__ < e__) {
      IOSByteArray *element = *b__++;
      
#line 135
      OrgBouncycastlePqcCryptoXmssXMSSUtil_copyBytesAtOffsetWithByteArray_withByteArray_withInt_(out, element, position);
      position += n;
    }
  }
  for (OrgBouncycastlePqcCryptoXmssXMSSNode * __strong element in nil_chk(authPath_)) {
    IOSByteArray *value = [((OrgBouncycastlePqcCryptoXmssXMSSNode *) nil_chk(element)) getValue];
    OrgBouncycastlePqcCryptoXmssXMSSUtil_copyBytesAtOffsetWithByteArray_withByteArray_withInt_(out, value, position);
    position += n;
  }
  return out;
}


#line 147
- (OrgBouncycastlePqcCryptoXmssXMSSParameters *)getParams {
  
#line 149
  return params_;
}


#line 152
- (OrgBouncycastlePqcCryptoXmssWOTSPlusSignature *)getWOTSPlusSignature {
  
#line 154
  return wotsPlusSignature_;
}


#line 157
- (id<JavaUtilList>)getAuthPath {
  
#line 159
  return authPath_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x4, -1, 0, -1, -1, -1, -1 },
    { NULL, "[B", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastlePqcCryptoXmssXMSSParameters;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastlePqcCryptoXmssWOTSPlusSignature;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, -1, -1, -1, 1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithOrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder:);
  methods[1].selector = @selector(toByteArray);
  methods[2].selector = @selector(getParams);
  methods[3].selector = @selector(getWOTSPlusSignature);
  methods[4].selector = @selector(getAuthPath);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "params_", "LOrgBouncycastlePqcCryptoXmssXMSSParameters;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "wotsPlusSignature_", "LOrgBouncycastlePqcCryptoXmssWOTSPlusSignature;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "authPath_", "LJavaUtilList;", .constantValue.asLong = 0, 0x12, -1, -1, 2, -1 },
  };
  static const void *ptrTable[] = { "LOrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder;", "()Ljava/util/List<Lorg/bouncycastle/pqc/crypto/xmss/XMSSNode;>;", "Ljava/util/List<Lorg/bouncycastle/pqc/crypto/xmss/XMSSNode;>;" };
  static const J2ObjcClassInfo _OrgBouncycastlePqcCryptoXmssXMSSReducedSignature = { "XMSSReducedSignature", "org.bouncycastle.pqc.crypto.xmss", ptrTable, methods, fields, 7, 0x1, 5, 3, -1, 0, -1, -1, -1 };
  return &_OrgBouncycastlePqcCryptoXmssXMSSReducedSignature;
}

@end


#line 17
void OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_initWithOrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder_(OrgBouncycastlePqcCryptoXmssXMSSReducedSignature *self, OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder *builder) {
  NSObject_init(self);
  self->params_ = ((OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder *) nil_chk(builder))->params_;
  if (self->params_ == nil) {
    
#line 22
    @throw new_JavaLangNullPointerException_initWithNSString_(@"params == null");
  }
  jint n = [self->params_ getTreeDigestSize];
  jint len = [((OrgBouncycastlePqcCryptoXmssWOTSPlusParameters *) nil_chk([((OrgBouncycastlePqcCryptoXmssWOTSPlus *) nil_chk([self->params_ getWOTSPlus])) getParams])) getLen];
  jint height = [self->params_ getHeight];
  IOSByteArray *reducedSignature = builder->reducedSignature_;
  if (reducedSignature != nil) {
    
#line 31
    jint signatureSize = len * n;
    jint authPathSize = height * n;
    jint totalSize = signatureSize + authPathSize;
    if (reducedSignature->size_ != totalSize) {
      
#line 36
      @throw new_JavaLangIllegalArgumentException_initWithNSString_(@"signature has wrong size");
    }
    jint position = 0;
    IOSObjectArray *wotsPlusSignature = [IOSObjectArray newArrayWithLength:len type:IOSClass_byteArray(1)];
    for (jint i = 0; i < wotsPlusSignature->size_; i++) {
      
#line 42
      (void) IOSObjectArray_Set(wotsPlusSignature, i, OrgBouncycastlePqcCryptoXmssXMSSUtil_extractBytesAtOffsetWithByteArray_withInt_withInt_(reducedSignature, position, n));
      position += n;
    }
    self->wotsPlusSignature_ = new_OrgBouncycastlePqcCryptoXmssWOTSPlusSignature_initPackagePrivateWithOrgBouncycastlePqcCryptoXmssWOTSPlusParameters_withByteArray2_([((OrgBouncycastlePqcCryptoXmssWOTSPlus *) nil_chk([self->params_ getWOTSPlus])) getParams], wotsPlusSignature);
    
#line 47
    id<JavaUtilList> nodeList = new_JavaUtilArrayList_init();
    for (jint i = 0; i < height; i++) {
      
#line 50
      [nodeList addWithId:new_OrgBouncycastlePqcCryptoXmssXMSSNode_initWithInt_withByteArray_(i, OrgBouncycastlePqcCryptoXmssXMSSUtil_extractBytesAtOffsetWithByteArray_withInt_withInt_(reducedSignature, position, n))];
      position += n;
    }
    self->authPath_ = nodeList;
  }
  else {
    
#line 58
    OrgBouncycastlePqcCryptoXmssWOTSPlusSignature *tmpSignature = builder->wotsPlusSignature_;
    if (tmpSignature != nil) {
      
#line 61
      self->wotsPlusSignature_ = tmpSignature;
    }
    else {
      
#line 65
      self->wotsPlusSignature_ = new_OrgBouncycastlePqcCryptoXmssWOTSPlusSignature_initPackagePrivateWithOrgBouncycastlePqcCryptoXmssWOTSPlusParameters_withByteArray2_([((OrgBouncycastlePqcCryptoXmssWOTSPlus *) nil_chk([self->params_ getWOTSPlus])) getParams], [IOSByteArray newArrayWithDimensions:2 lengths:(jint[]){ len, n }]);
    }
    id<JavaUtilList> tmpAuthPath = builder->authPath_;
    if (tmpAuthPath != nil) {
      
#line 70
      if ([tmpAuthPath size] != height) {
        
#line 72
        @throw new_JavaLangIllegalArgumentException_initWithNSString_(@"size of authPath needs to be equal to height of tree");
      }
      self->authPath_ = tmpAuthPath;
    }
    else {
      
#line 78
      self->authPath_ = new_JavaUtilArrayList_init();
    }
  }
}


#line 17
OrgBouncycastlePqcCryptoXmssXMSSReducedSignature *new_OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_initWithOrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder_(OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder *builder) {
  J2OBJC_NEW_IMPL(OrgBouncycastlePqcCryptoXmssXMSSReducedSignature, initWithOrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder_, builder)
}


#line 17
OrgBouncycastlePqcCryptoXmssXMSSReducedSignature *create_OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_initWithOrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder_(OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder *builder) {
  J2OBJC_CREATE_IMPL(OrgBouncycastlePqcCryptoXmssXMSSReducedSignature, initWithOrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder_, builder)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastlePqcCryptoXmssXMSSReducedSignature)

#line 1 "/Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/org/bouncycastle/pqc/crypto/xmss/XMSSReducedSignature.java"


#line 83
@implementation OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder


#line 93
- (instancetype)initWithOrgBouncycastlePqcCryptoXmssXMSSParameters:(OrgBouncycastlePqcCryptoXmssXMSSParameters *)params {
  OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder_initWithOrgBouncycastlePqcCryptoXmssXMSSParameters_(self, params);
  return self;
}

- (OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder *)withWOTSPlusSignatureWithOrgBouncycastlePqcCryptoXmssWOTSPlusSignature:(OrgBouncycastlePqcCryptoXmssWOTSPlusSignature *)val {
  
#line 100
  wotsPlusSignature_ = val;
  return self;
}


#line 104
- (OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder *)withAuthPathWithJavaUtilList:(id<JavaUtilList>)val {
  
#line 106
  authPath_ = val;
  return self;
}


#line 110
- (OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder *)withReducedSignatureWithByteArray:(IOSByteArray *)val {
  
#line 112
  reducedSignature_ = OrgBouncycastlePqcCryptoXmssXMSSUtil_cloneArrayWithByteArray_(val);
  return self;
}


#line 116
- (OrgBouncycastlePqcCryptoXmssXMSSReducedSignature *)build {
  
#line 118
  return new_OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_initWithOrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder_(self);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder;", 0x1, 3, 4, -1, 5, -1, -1 },
    { NULL, "LOrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder;", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastlePqcCryptoXmssXMSSReducedSignature;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithOrgBouncycastlePqcCryptoXmssXMSSParameters:);
  methods[1].selector = @selector(withWOTSPlusSignatureWithOrgBouncycastlePqcCryptoXmssWOTSPlusSignature:);
  methods[2].selector = @selector(withAuthPathWithJavaUtilList:);
  methods[3].selector = @selector(withReducedSignatureWithByteArray:);
  methods[4].selector = @selector(build);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "params_", "LOrgBouncycastlePqcCryptoXmssXMSSParameters;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "wotsPlusSignature_", "LOrgBouncycastlePqcCryptoXmssWOTSPlusSignature;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "authPath_", "LJavaUtilList;", .constantValue.asLong = 0, 0x2, -1, -1, 8, -1 },
    { "reducedSignature_", "[B", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LOrgBouncycastlePqcCryptoXmssXMSSParameters;", "withWOTSPlusSignature", "LOrgBouncycastlePqcCryptoXmssWOTSPlusSignature;", "withAuthPath", "LJavaUtilList;", "(Ljava/util/List<Lorg/bouncycastle/pqc/crypto/xmss/XMSSNode;>;)Lorg/bouncycastle/pqc/crypto/xmss/XMSSReducedSignature$Builder;", "withReducedSignature", "[B", "Ljava/util/List<Lorg/bouncycastle/pqc/crypto/xmss/XMSSNode;>;", "LOrgBouncycastlePqcCryptoXmssXMSSReducedSignature;" };
  static const J2ObjcClassInfo _OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder = { "Builder", "org.bouncycastle.pqc.crypto.xmss", ptrTable, methods, fields, 7, 0x9, 5, 4, 9, -1, -1, -1, -1 };
  return &_OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder;
}

@end


#line 93
void OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder_initWithOrgBouncycastlePqcCryptoXmssXMSSParameters_(OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder *self, OrgBouncycastlePqcCryptoXmssXMSSParameters *params) {
  NSObject_init(self);
  self->wotsPlusSignature_ =
#line 89
  nil;
  self->authPath_ = nil;
  self->reducedSignature_ = nil;
  
#line 95
  self->params_ = params;
}


#line 93
OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder *new_OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder_initWithOrgBouncycastlePqcCryptoXmssXMSSParameters_(OrgBouncycastlePqcCryptoXmssXMSSParameters *params) {
  J2OBJC_NEW_IMPL(OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder, initWithOrgBouncycastlePqcCryptoXmssXMSSParameters_, params)
}


#line 93
OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder *create_OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder_initWithOrgBouncycastlePqcCryptoXmssXMSSParameters_(OrgBouncycastlePqcCryptoXmssXMSSParameters *params) {
  J2OBJC_CREATE_IMPL(OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder, initWithOrgBouncycastlePqcCryptoXmssXMSSParameters_, params)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastlePqcCryptoXmssXMSSReducedSignature_Builder)
