//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/com/aowagie/text/pdf/parser/ContentOperator.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAowagieTextPdfParserContentOperator")
#ifdef RESTRICT_ComAowagieTextPdfParserContentOperator
#define INCLUDE_ALL_ComAowagieTextPdfParserContentOperator 0
#else
#define INCLUDE_ALL_ComAowagieTextPdfParserContentOperator 1
#endif
#undef RESTRICT_ComAowagieTextPdfParserContentOperator

#if !defined (ComAowagieTextPdfParserContentOperator_) && (INCLUDE_ALL_ComAowagieTextPdfParserContentOperator || defined(INCLUDE_ComAowagieTextPdfParserContentOperator))
#define ComAowagieTextPdfParserContentOperator_

@class ComAowagieTextPdfParserPdfContentStreamProcessor;
@class ComAowagieTextPdfPdfLiteral;
@class JavaUtilArrayList;

/*!
 @brief Interface implemented by a series of content operators
 @since 2.1.4
 */
@protocol ComAowagieTextPdfParserContentOperator < JavaObject >

/*!
 @brief Invokes a content operator.
 @param processor the processor that is dealing with the PDF content
 @param operator_ the literal PDF syntax of the operator
 @param operands the operands that come with the operator
 */
- (void)invokeWithComAowagieTextPdfParserPdfContentStreamProcessor:(ComAowagieTextPdfParserPdfContentStreamProcessor *)processor
                                   withComAowagieTextPdfPdfLiteral:(ComAowagieTextPdfPdfLiteral *)operator_
                                             withJavaUtilArrayList:(JavaUtilArrayList *)operands;

@end

J2OBJC_EMPTY_STATIC_INIT(ComAowagieTextPdfParserContentOperator)

J2OBJC_TYPE_LITERAL_HEADER(ComAowagieTextPdfParserContentOperator)

#endif

#pragma pop_macro("INCLUDE_ALL_ComAowagieTextPdfParserContentOperator")
