//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/org/bouncycastle/math/ec/custom/sec/SecT233K1Curve.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/math/BigInteger.h"
#include "org/bouncycastle/math/ec/AbstractECLookupTable.h"
#include "org/bouncycastle/math/ec/ECConstants.h"
#include "org/bouncycastle/math/ec/ECCurve.h"
#include "org/bouncycastle/math/ec/ECFieldElement.h"
#include "org/bouncycastle/math/ec/ECLookupTable.h"
#include "org/bouncycastle/math/ec/ECMultiplier.h"
#include "org/bouncycastle/math/ec/ECPoint.h"
#include "org/bouncycastle/math/ec/WTauNafMultiplier.h"
#include "org/bouncycastle/math/ec/custom/sec/SecT233FieldElement.h"
#include "org/bouncycastle/math/ec/custom/sec/SecT233K1Curve.h"
#include "org/bouncycastle/math/ec/custom/sec/SecT233K1Point.h"
#include "org/bouncycastle/math/raw/Nat256.h"
#include "org/bouncycastle/util/encoders/Hex.h"

#if !__has_feature(objc_arc)
#error "org/bouncycastle/math/ec/custom/sec/SecT233K1Curve must be compiled with ARC (-fobjc-arc)"
#endif

inline jint OrgBouncycastleMathEcCustomSecSecT233K1Curve_get_SECT233K1_DEFAULT_COORDS(void);
#define OrgBouncycastleMathEcCustomSecSecT233K1Curve_SECT233K1_DEFAULT_COORDS 6
J2OBJC_STATIC_FIELD_CONSTANT(OrgBouncycastleMathEcCustomSecSecT233K1Curve, SECT233K1_DEFAULT_COORDS, jint)

inline IOSObjectArray *OrgBouncycastleMathEcCustomSecSecT233K1Curve_get_SECT233K1_AFFINE_ZS(void);
static IOSObjectArray *OrgBouncycastleMathEcCustomSecSecT233K1Curve_SECT233K1_AFFINE_ZS;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgBouncycastleMathEcCustomSecSecT233K1Curve, SECT233K1_AFFINE_ZS, IOSObjectArray *)

@interface OrgBouncycastleMathEcCustomSecSecT233K1Curve_1 : OrgBouncycastleMathEcAbstractECLookupTable {
 @public
  OrgBouncycastleMathEcCustomSecSecT233K1Curve *this$0_;
  jint val$len_;
  IOSLongArray *val$table_;
}

- (instancetype)initWithOrgBouncycastleMathEcCustomSecSecT233K1Curve:(OrgBouncycastleMathEcCustomSecSecT233K1Curve *)outer$
                                                             withInt:(jint)capture$0
                                                       withLongArray:(IOSLongArray *)capture$1;

- (jint)getSize;

- (OrgBouncycastleMathEcECPoint *)lookupWithInt:(jint)index;

- (OrgBouncycastleMathEcECPoint *)lookupVarWithInt:(jint)index;

- (OrgBouncycastleMathEcECPoint *)createPointWithLongArray:(IOSLongArray *)x
                                             withLongArray:(IOSLongArray *)y;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleMathEcCustomSecSecT233K1Curve_1)

__attribute__((unused)) static void OrgBouncycastleMathEcCustomSecSecT233K1Curve_1_initWithOrgBouncycastleMathEcCustomSecSecT233K1Curve_withInt_withLongArray_(OrgBouncycastleMathEcCustomSecSecT233K1Curve_1 *self, OrgBouncycastleMathEcCustomSecSecT233K1Curve *outer$, jint capture$0, IOSLongArray *capture$1);

__attribute__((unused)) static OrgBouncycastleMathEcCustomSecSecT233K1Curve_1 *new_OrgBouncycastleMathEcCustomSecSecT233K1Curve_1_initWithOrgBouncycastleMathEcCustomSecSecT233K1Curve_withInt_withLongArray_(OrgBouncycastleMathEcCustomSecSecT233K1Curve *outer$, jint capture$0, IOSLongArray *capture$1) NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgBouncycastleMathEcCustomSecSecT233K1Curve_1 *create_OrgBouncycastleMathEcCustomSecSecT233K1Curve_1_initWithOrgBouncycastleMathEcCustomSecSecT233K1Curve_withInt_withLongArray_(OrgBouncycastleMathEcCustomSecSecT233K1Curve *outer$, jint capture$0, IOSLongArray *capture$1);

__attribute__((unused)) static OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcCustomSecSecT233K1Curve_1_createPointWithLongArray_withLongArray_(OrgBouncycastleMathEcCustomSecSecT233K1Curve_1 *self, IOSLongArray *x, IOSLongArray *y);

#line 1 "/Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/org/bouncycastle/math/ec/custom/sec/SecT233K1Curve.java"

J2OBJC_INITIALIZED_DEFN(OrgBouncycastleMathEcCustomSecSecT233K1Curve)


#line 17
@implementation OrgBouncycastleMathEcCustomSecSecT233K1Curve

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 24
- (instancetype)init {
  OrgBouncycastleMathEcCustomSecSecT233K1Curve_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END


#line 38
- (OrgBouncycastleMathEcECCurve *)cloneCurve {
  
#line 41
  return new_OrgBouncycastleMathEcCustomSecSecT233K1Curve_init();
}

- (jboolean)supportsCoordinateSystemWithInt:(jint)coord {
  
#line 47
  switch (coord) {
    
#line 49
    case OrgBouncycastleMathEcECCurve_COORD_LAMBDA_PROJECTIVE:
    return true;
    default:
    return false;
  }
}


#line 56
- (id<OrgBouncycastleMathEcECMultiplier>)createDefaultMultiplier {
  
#line 59
  return new_OrgBouncycastleMathEcWTauNafMultiplier_init();
}

- (jint)getFieldSize {
  
#line 65
  return 233;
}

- (OrgBouncycastleMathEcECFieldElement *)fromBigIntegerWithJavaMathBigInteger:(JavaMathBigInteger *)x {
  
#line 71
  return new_OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithJavaMathBigInteger_(x);
}

- (OrgBouncycastleMathEcECPoint *)createRawPointWithOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)x
                                                withOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)y {
  
#line 77
  return new_OrgBouncycastleMathEcCustomSecSecT233K1Point_initWithOrgBouncycastleMathEcECCurve_withOrgBouncycastleMathEcECFieldElement_withOrgBouncycastleMathEcECFieldElement_(self, x, y);
}


#line 80
- (OrgBouncycastleMathEcECPoint *)createRawPointWithOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)x
                                                withOrgBouncycastleMathEcECFieldElement:(OrgBouncycastleMathEcECFieldElement *)y
                                           withOrgBouncycastleMathEcECFieldElementArray:(IOSObjectArray *)zs {
  return new_OrgBouncycastleMathEcCustomSecSecT233K1Point_initWithOrgBouncycastleMathEcECCurve_withOrgBouncycastleMathEcECFieldElement_withOrgBouncycastleMathEcECFieldElement_withOrgBouncycastleMathEcECFieldElementArray_(self, x, y, zs);
}

- (OrgBouncycastleMathEcECPoint *)getInfinity {
  
#line 89
  return infinity_;
}

- (jboolean)isKoblitz {
  
#line 95
  return true;
}

- (jint)getM {
  
#line 100
  return 233;
}


#line 103
- (jboolean)isTrinomial {
  
#line 105
  return true;
}


#line 108
- (jint)getK1 {
  
#line 110
  return 74;
}


#line 113
- (jint)getK2 {
  
#line 115
  return 0;
}


#line 118
- (jint)getK3 {
  
#line 120
  return 0;
}


#line 123
- (id<OrgBouncycastleMathEcECLookupTable>)createCacheSafeLookupTableWithOrgBouncycastleMathEcECPointArray:(IOSObjectArray *)points
                                                                                                  withInt:(jint)off
                                                                                                  withInt:(jint)len {
  jint FE_LONGS = 4;
  
#line 128
  IOSLongArray *table = [IOSLongArray newArrayWithLength:len * FE_LONGS * 2];
  {
    jint pos = 0;
    for (jint i = 0; i < len; ++i) {
      
#line 133
      OrgBouncycastleMathEcECPoint *p = IOSObjectArray_Get(nil_chk(points), off + i);
      OrgBouncycastleMathRawNat256_copy64WithLongArray_withInt_withLongArray_withInt_(((OrgBouncycastleMathEcCustomSecSecT233FieldElement *) nil_chk(((OrgBouncycastleMathEcCustomSecSecT233FieldElement *) cast_chk([((OrgBouncycastleMathEcECPoint *) nil_chk(p)) getRawXCoord], [OrgBouncycastleMathEcCustomSecSecT233FieldElement class]))))->x_, 0, table, pos);
      
#line 134
      pos += FE_LONGS;
      OrgBouncycastleMathRawNat256_copy64WithLongArray_withInt_withLongArray_withInt_(((OrgBouncycastleMathEcCustomSecSecT233FieldElement *) nil_chk(((OrgBouncycastleMathEcCustomSecSecT233FieldElement *) cast_chk([p getRawYCoord], [OrgBouncycastleMathEcCustomSecSecT233FieldElement class]))))->x_, 0, table, pos);
      
#line 135
      pos += FE_LONGS;
    }
  }
  
#line 139
  return new_OrgBouncycastleMathEcCustomSecSecT233K1Curve_1_initWithOrgBouncycastleMathEcCustomSecSecT233K1Curve_withInt_withLongArray_(self, len, table);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECCurve;", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECMultiplier;", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECFieldElement;", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0x4, 4, 5, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0x4, 4, 6, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECLookupTable;", 0x1, 7, 8, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(cloneCurve);
  methods[2].selector = @selector(supportsCoordinateSystemWithInt:);
  methods[3].selector = @selector(createDefaultMultiplier);
  methods[4].selector = @selector(getFieldSize);
  methods[5].selector = @selector(fromBigIntegerWithJavaMathBigInteger:);
  methods[6].selector = @selector(createRawPointWithOrgBouncycastleMathEcECFieldElement:withOrgBouncycastleMathEcECFieldElement:);
  methods[7].selector = @selector(createRawPointWithOrgBouncycastleMathEcECFieldElement:withOrgBouncycastleMathEcECFieldElement:withOrgBouncycastleMathEcECFieldElementArray:);
  methods[8].selector = @selector(getInfinity);
  methods[9].selector = @selector(isKoblitz);
  methods[10].selector = @selector(getM);
  methods[11].selector = @selector(isTrinomial);
  methods[12].selector = @selector(getK1);
  methods[13].selector = @selector(getK2);
  methods[14].selector = @selector(getK3);
  methods[15].selector = @selector(createCacheSafeLookupTableWithOrgBouncycastleMathEcECPointArray:withInt:withInt:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "SECT233K1_DEFAULT_COORDS", "I", .constantValue.asInt = OrgBouncycastleMathEcCustomSecSecT233K1Curve_SECT233K1_DEFAULT_COORDS, 0x1a, -1, -1, -1, -1 },
    { "SECT233K1_AFFINE_ZS", "[LOrgBouncycastleMathEcECFieldElement;", .constantValue.asLong = 0, 0x1a, -1, 9, -1, -1 },
    { "infinity_", "LOrgBouncycastleMathEcCustomSecSecT233K1Point;", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "supportsCoordinateSystem", "I", "fromBigInteger", "LJavaMathBigInteger;", "createRawPoint", "LOrgBouncycastleMathEcECFieldElement;LOrgBouncycastleMathEcECFieldElement;", "LOrgBouncycastleMathEcECFieldElement;LOrgBouncycastleMathEcECFieldElement;[LOrgBouncycastleMathEcECFieldElement;", "createCacheSafeLookupTable", "[LOrgBouncycastleMathEcECPoint;II", &OrgBouncycastleMathEcCustomSecSecT233K1Curve_SECT233K1_AFFINE_ZS };
  static const J2ObjcClassInfo _OrgBouncycastleMathEcCustomSecSecT233K1Curve = { "SecT233K1Curve", "org.bouncycastle.math.ec.custom.sec", ptrTable, methods, fields, 7, 0x1, 16, 3, -1, -1, -1, -1, -1 };
  return &_OrgBouncycastleMathEcCustomSecSecT233K1Curve;
}

+ (void)initialize {
  if (self == [OrgBouncycastleMathEcCustomSecSecT233K1Curve class]) {
    OrgBouncycastleMathEcCustomSecSecT233K1Curve_SECT233K1_AFFINE_ZS = [IOSObjectArray newArrayWithObjects:(id[]){ create_OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithJavaMathBigInteger_(JreLoadStatic(OrgBouncycastleMathEcECConstants, ONE)) } count:1 type:OrgBouncycastleMathEcECFieldElement_class_()];
    J2OBJC_SET_INITIALIZED(OrgBouncycastleMathEcCustomSecSecT233K1Curve)
  }
}

@end


#line 24
void OrgBouncycastleMathEcCustomSecSecT233K1Curve_init(OrgBouncycastleMathEcCustomSecSecT233K1Curve *self) {
  OrgBouncycastleMathEcECCurve_AbstractF2m_initWithInt_withInt_withInt_withInt_(self,
#line 26
  233, 74, 0, 0);
  
#line 28
  self->infinity_ = new_OrgBouncycastleMathEcCustomSecSecT233K1Point_initWithOrgBouncycastleMathEcECCurve_withOrgBouncycastleMathEcECFieldElement_withOrgBouncycastleMathEcECFieldElement_(self, nil, nil);
  
#line 30
  self->a_ = [self fromBigIntegerWithJavaMathBigInteger:JavaMathBigInteger_valueOfWithLong_(0)];
  self->b_ = [self fromBigIntegerWithJavaMathBigInteger:JavaMathBigInteger_valueOfWithLong_(1)];
  self->order_ = new_JavaMathBigInteger_initWithInt_withByteArray_(1, OrgBouncycastleUtilEncodersHex_decodeStrictWithNSString_(@"8000000000000000000000000000069D5BB915BCD46EFB1AD5F173ABDF"));
  self->cofactor_ = JavaMathBigInteger_valueOfWithLong_(4);
  
#line 35
  self->coord_ = OrgBouncycastleMathEcCustomSecSecT233K1Curve_SECT233K1_DEFAULT_COORDS;
}


#line 24
OrgBouncycastleMathEcCustomSecSecT233K1Curve *new_OrgBouncycastleMathEcCustomSecSecT233K1Curve_init() {
  J2OBJC_NEW_IMPL(OrgBouncycastleMathEcCustomSecSecT233K1Curve, init)
}


#line 24
OrgBouncycastleMathEcCustomSecSecT233K1Curve *create_OrgBouncycastleMathEcCustomSecSecT233K1Curve_init() {
  J2OBJC_CREATE_IMPL(OrgBouncycastleMathEcCustomSecSecT233K1Curve, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastleMathEcCustomSecSecT233K1Curve)

#line 1 "/Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/org/bouncycastle/math/ec/custom/sec/SecT233K1Curve.java"


#line 140
@implementation OrgBouncycastleMathEcCustomSecSecT233K1Curve_1


#line 140
- (instancetype)initWithOrgBouncycastleMathEcCustomSecSecT233K1Curve:(OrgBouncycastleMathEcCustomSecSecT233K1Curve *)outer$
                                                             withInt:(jint)capture$0
                                                       withLongArray:(IOSLongArray *)capture$1 {
  OrgBouncycastleMathEcCustomSecSecT233K1Curve_1_initWithOrgBouncycastleMathEcCustomSecSecT233K1Curve_withInt_withLongArray_(self, outer$, capture$0, capture$1);
  return self;
}


#line 141
- (jint)getSize {
  
#line 144
  return val$len_;
}

- (OrgBouncycastleMathEcECPoint *)lookupWithInt:(jint)index {
  
#line 150
  IOSLongArray *x = OrgBouncycastleMathRawNat256_create64();
  
#line 150
  IOSLongArray *y = OrgBouncycastleMathRawNat256_create64();
  jint pos = 0;
  
#line 153
  for (jint i = 0; i < val$len_; ++i) {
    
#line 155
    jlong MASK = JreRShift32(((i ^ index) - 1), 31);
    
#line 157
    for (jint j = 0; j < 4; ++j) {
      
#line 159
      *IOSLongArray_GetRef(nil_chk(x), j) ^= IOSLongArray_Get(nil_chk(val$table_), pos + j) & MASK;
      *IOSLongArray_GetRef(nil_chk(y), j) ^= IOSLongArray_Get(val$table_, pos + 4 + j) & MASK;
    }
    
#line 163
    pos += (4 * 2);
  }
  
#line 166
  return OrgBouncycastleMathEcCustomSecSecT233K1Curve_1_createPointWithLongArray_withLongArray_(self, x, y);
}


#line 169
- (OrgBouncycastleMathEcECPoint *)lookupVarWithInt:(jint)index {
  
#line 172
  IOSLongArray *x = OrgBouncycastleMathRawNat256_create64();
  
#line 172
  IOSLongArray *y = OrgBouncycastleMathRawNat256_create64();
  jint pos = index * 4 * 2;
  
#line 175
  for (jint j = 0; j < 4; ++j) {
    
#line 177
    *IOSLongArray_GetRef(nil_chk(x), j) = IOSLongArray_Get(nil_chk(val$table_), pos + j);
    *IOSLongArray_GetRef(nil_chk(y), j) = IOSLongArray_Get(val$table_, pos + 4 + j);
  }
  
#line 181
  return OrgBouncycastleMathEcCustomSecSecT233K1Curve_1_createPointWithLongArray_withLongArray_(self, x, y);
}


#line 184
- (OrgBouncycastleMathEcECPoint *)createPointWithLongArray:(IOSLongArray *)x
                                             withLongArray:(IOSLongArray *)y {
  return OrgBouncycastleMathEcCustomSecSecT233K1Curve_1_createPointWithLongArray_withLongArray_(self, x, y);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0x1, 3, 2, -1, -1, -1, -1 },
    { NULL, "LOrgBouncycastleMathEcECPoint;", 0x2, 4, 5, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithOrgBouncycastleMathEcCustomSecSecT233K1Curve:withInt:withLongArray:);
  methods[1].selector = @selector(getSize);
  methods[2].selector = @selector(lookupWithInt:);
  methods[3].selector = @selector(lookupVarWithInt:);
  methods[4].selector = @selector(createPointWithLongArray:withLongArray:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LOrgBouncycastleMathEcCustomSecSecT233K1Curve;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "val$len_", "I", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "val$table_", "[J", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LOrgBouncycastleMathEcCustomSecSecT233K1Curve;I[J", "lookup", "I", "lookupVar", "createPoint", "[J[J", "LOrgBouncycastleMathEcCustomSecSecT233K1Curve;", "createCacheSafeLookupTableWithOrgBouncycastleMathEcECPointArray:withInt:withInt:" };
  static const J2ObjcClassInfo _OrgBouncycastleMathEcCustomSecSecT233K1Curve_1 = { "", "org.bouncycastle.math.ec.custom.sec", ptrTable, methods, fields, 7, 0x8000, 5, 3, 6, -1, 7, -1, -1 };
  return &_OrgBouncycastleMathEcCustomSecSecT233K1Curve_1;
}

@end


#line 140
void OrgBouncycastleMathEcCustomSecSecT233K1Curve_1_initWithOrgBouncycastleMathEcCustomSecSecT233K1Curve_withInt_withLongArray_(OrgBouncycastleMathEcCustomSecSecT233K1Curve_1 *self, OrgBouncycastleMathEcCustomSecSecT233K1Curve *outer$, jint capture$0, IOSLongArray *capture$1) {
  self->this$0_ = outer$;
  self->val$len_ = capture$0;
  self->val$table_ = capture$1;
  OrgBouncycastleMathEcAbstractECLookupTable_init(self);
}


#line 140
OrgBouncycastleMathEcCustomSecSecT233K1Curve_1 *new_OrgBouncycastleMathEcCustomSecSecT233K1Curve_1_initWithOrgBouncycastleMathEcCustomSecSecT233K1Curve_withInt_withLongArray_(OrgBouncycastleMathEcCustomSecSecT233K1Curve *outer$, jint capture$0, IOSLongArray *capture$1) {
  J2OBJC_NEW_IMPL(OrgBouncycastleMathEcCustomSecSecT233K1Curve_1, initWithOrgBouncycastleMathEcCustomSecSecT233K1Curve_withInt_withLongArray_, outer$, capture$0, capture$1)
}


#line 140
OrgBouncycastleMathEcCustomSecSecT233K1Curve_1 *create_OrgBouncycastleMathEcCustomSecSecT233K1Curve_1_initWithOrgBouncycastleMathEcCustomSecSecT233K1Curve_withInt_withLongArray_(OrgBouncycastleMathEcCustomSecSecT233K1Curve *outer$, jint capture$0, IOSLongArray *capture$1) {
  J2OBJC_CREATE_IMPL(OrgBouncycastleMathEcCustomSecSecT233K1Curve_1, initWithOrgBouncycastleMathEcCustomSecSecT233K1Curve_withInt_withLongArray_, outer$, capture$0, capture$1)
}


#line 184
OrgBouncycastleMathEcECPoint *OrgBouncycastleMathEcCustomSecSecT233K1Curve_1_createPointWithLongArray_withLongArray_(OrgBouncycastleMathEcCustomSecSecT233K1Curve_1 *self, IOSLongArray *x, IOSLongArray *y) {
  
#line 186
  return [self->this$0_ createRawPointWithOrgBouncycastleMathEcECFieldElement:new_OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithLongArray_(x) withOrgBouncycastleMathEcECFieldElement:new_OrgBouncycastleMathEcCustomSecSecT233FieldElement_initWithLongArray_(y) withOrgBouncycastleMathEcECFieldElementArray:JreLoadStatic(OrgBouncycastleMathEcCustomSecSecT233K1Curve, SECT233K1_AFFINE_ZS)];
}
