//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/es/gob/jmulticard/card/dnie/Dnie3Cwa14890Constants.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "es/gob/jmulticard/card/dnie/Dnie3Cwa14890Constants.h"
#include "java/lang/System.h"
#include "java/security/PublicKey.h"

#if !__has_feature(objc_arc)
#error "es/gob/jmulticard/card/dnie/Dnie3Cwa14890Constants must be compiled with ARC (-fobjc-arc)"
#endif

#pragma clang diagnostic ignored "-Wprotocol"

/*!
 @brief Referencia al fichero en donde reside la clave p&uacute;blica de la autoridad certificadora
  ra&iacute;z de la jerarqu&iacute;a de certificados verificables por la tarjeta.
 (<i>pk-RCA-AUT-keyRef</i>).
 */
inline IOSByteArray *EsGobJmulticardCardDnieDnie3Cwa14890Constants_get_REF_C_CV_CA_PUBLIC_KEY(void);
static IOSByteArray *EsGobJmulticardCardDnieDnie3Cwa14890Constants_REF_C_CV_CA_PUBLIC_KEY;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EsGobJmulticardCardDnieDnie3Cwa14890Constants, REF_C_CV_CA_PUBLIC_KEY, IOSByteArray *)

/*!
 @brief Referencia al fichero en donde reside la clave privada de componente.
 (<i>sk-ICC-AUT-keyRef</i>).
 */
inline IOSByteArray *EsGobJmulticardCardDnieDnie3Cwa14890Constants_get_REF_ICC_PRIVATE_KEY(void);
static IOSByteArray *EsGobJmulticardCardDnieDnie3Cwa14890Constants_REF_ICC_PRIVATE_KEY;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EsGobJmulticardCardDnieDnie3Cwa14890Constants, REF_ICC_PRIVATE_KEY, IOSByteArray *)

/*!
 @brief Clave p&uacute;blica del certificado de componente de la tarjeta.
 (<i>pk-RCAicc</i>).
 */
inline id<JavaSecurityPublicKey> EsGobJmulticardCardDnieDnie3Cwa14890Constants_get_CA_COMPONENT_PUBLIC_KEY(void);
static id<JavaSecurityPublicKey> EsGobJmulticardCardDnieDnie3Cwa14890Constants_CA_COMPONENT_PUBLIC_KEY;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EsGobJmulticardCardDnieDnie3Cwa14890Constants, CA_COMPONENT_PUBLIC_KEY, id<JavaSecurityPublicKey>)

@interface EsGobJmulticardCardDnieDnie3Cwa14890Constants_1 : NSObject < JavaSecurityPublicKey > {
 @public
  IOSByteArray *encoded_;
}

- (instancetype)init;

- (NSString *)getFormat;

- (IOSByteArray *)getEncoded;

- (NSString *)getAlgorithm;

@end

J2OBJC_EMPTY_STATIC_INIT(EsGobJmulticardCardDnieDnie3Cwa14890Constants_1)

J2OBJC_FIELD_SETTER(EsGobJmulticardCardDnieDnie3Cwa14890Constants_1, encoded_, IOSByteArray *)

inline jlong EsGobJmulticardCardDnieDnie3Cwa14890Constants_1_get_serialVersionUID(void);
#define EsGobJmulticardCardDnieDnie3Cwa14890Constants_1_serialVersionUID -143874096089393139LL
J2OBJC_STATIC_FIELD_CONSTANT(EsGobJmulticardCardDnieDnie3Cwa14890Constants_1, serialVersionUID, jlong)

__attribute__((unused)) static void EsGobJmulticardCardDnieDnie3Cwa14890Constants_1_init(EsGobJmulticardCardDnieDnie3Cwa14890Constants_1 *self);

__attribute__((unused)) static EsGobJmulticardCardDnieDnie3Cwa14890Constants_1 *new_EsGobJmulticardCardDnieDnie3Cwa14890Constants_1_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static EsGobJmulticardCardDnieDnie3Cwa14890Constants_1 *create_EsGobJmulticardCardDnieDnie3Cwa14890Constants_1_init(void);

#line 1 "/Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/es/gob/jmulticard/card/dnie/Dnie3Cwa14890Constants.java"

J2OBJC_INITIALIZED_DEFN(EsGobJmulticardCardDnieDnie3Cwa14890Constants)


#line 49
@implementation EsGobJmulticardCardDnieDnie3Cwa14890Constants

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 49
- (instancetype)init {
  EsGobJmulticardCardDnieDnie3Cwa14890Constants_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END


#line 108
- (IOSByteArray *)getRefCCvCaPublicKey {
  
#line 110
  return EsGobJmulticardCardDnieDnie3Cwa14890Constants_REF_C_CV_CA_PUBLIC_KEY;
}


#line 113
- (IOSByteArray *)getRefIccPrivateKey {
  
#line 115
  return EsGobJmulticardCardDnieDnie3Cwa14890Constants_REF_ICC_PRIVATE_KEY;
}


#line 118
- (id<JavaSecurityPublicKey>)getCaComponentPublicKey {
  
#line 120
  return EsGobJmulticardCardDnieDnie3Cwa14890Constants_CA_COMPONENT_PUBLIC_KEY;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[B", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[B", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaSecurityPublicKey;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getRefCCvCaPublicKey);
  methods[2].selector = @selector(getRefIccPrivateKey);
  methods[3].selector = @selector(getCaComponentPublicKey);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "REF_C_CV_CA_PUBLIC_KEY", "[B", .constantValue.asLong = 0, 0x1a, -1, 0, -1, -1 },
    { "REF_ICC_PRIVATE_KEY", "[B", .constantValue.asLong = 0, 0x1a, -1, 1, -1, -1 },
    { "CA_COMPONENT_PUBLIC_KEY", "LJavaSecurityPublicKey;", .constantValue.asLong = 0, 0x1a, -1, 2, -1, -1 },
  };
  static const void *ptrTable[] = { &EsGobJmulticardCardDnieDnie3Cwa14890Constants_REF_C_CV_CA_PUBLIC_KEY, &EsGobJmulticardCardDnieDnie3Cwa14890Constants_REF_ICC_PRIVATE_KEY, &EsGobJmulticardCardDnieDnie3Cwa14890Constants_CA_COMPONENT_PUBLIC_KEY };
  static const J2ObjcClassInfo _EsGobJmulticardCardDnieDnie3Cwa14890Constants = { "Dnie3Cwa14890Constants", "es.gob.jmulticard.card.dnie", ptrTable, methods, fields, 7, 0x401, 4, 3, -1, -1, -1, -1, -1 };
  return &_EsGobJmulticardCardDnieDnie3Cwa14890Constants;
}

+ (void)initialize {
  if (self == [EsGobJmulticardCardDnieDnie3Cwa14890Constants class]) {
    EsGobJmulticardCardDnieDnie3Cwa14890Constants_REF_C_CV_CA_PUBLIC_KEY = [IOSByteArray newArrayWithBytes:(jbyte[]){
#line 55
      (jbyte) (jint) 0x02, (jbyte) (jint) 0x0f } count:2];
      EsGobJmulticardCardDnieDnie3Cwa14890Constants_REF_ICC_PRIVATE_KEY = [IOSByteArray newArrayWithBytes:(jbyte[]){
#line 61
        (jbyte) (jint) 0x02, (jbyte) (jint) 0x1f } count:2];
        EsGobJmulticardCardDnieDnie3Cwa14890Constants_CA_COMPONENT_PUBLIC_KEY = new_EsGobJmulticardCardDnieDnie3Cwa14890Constants_1_init();
        J2OBJC_SET_INITIALIZED(EsGobJmulticardCardDnieDnie3Cwa14890Constants)
      }
    }

@end


#line 49
void EsGobJmulticardCardDnieDnie3Cwa14890Constants_init(EsGobJmulticardCardDnieDnie3Cwa14890Constants *self) {
  NSObject_init(self);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EsGobJmulticardCardDnieDnie3Cwa14890Constants)

#line 1 "/Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/es/gob/jmulticard/card/dnie/Dnie3Cwa14890Constants.java"


#line 66
@implementation EsGobJmulticardCardDnieDnie3Cwa14890Constants_1

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 66
- (instancetype)init {
  EsGobJmulticardCardDnieDnie3Cwa14890Constants_1_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END


#line 90
- (NSString *)getFormat {
  
#line 92
  return @"X.509";
}


#line 95
- (IOSByteArray *)getEncoded {
  
#line 97
  IOSByteArray *out = [IOSByteArray newArrayWithLength:((IOSByteArray *) nil_chk(encoded_))->size_];
  JavaLangSystem_arraycopyWithId_withInt_withId_withInt_withInt_(encoded_, 0, out, 0, encoded_->size_);
  return JreRetainedLocalValue(out);
}


#line 102
- (NSString *)getAlgorithm {
  
#line 104
  return @"RSA";
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[B", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getFormat);
  methods[2].selector = @selector(getEncoded);
  methods[3].selector = @selector(getAlgorithm);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "J", .constantValue.asLong = EsGobJmulticardCardDnieDnie3Cwa14890Constants_1_serialVersionUID, 0x1a, -1, -1, -1, -1 },
    { "encoded_", "[B", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LEsGobJmulticardCardDnieDnie3Cwa14890Constants;" };
  static const J2ObjcClassInfo _EsGobJmulticardCardDnieDnie3Cwa14890Constants_1 = { "", "es.gob.jmulticard.card.dnie", ptrTable, methods, fields, 7, 0x8000, 4, 2, 0, -1, -1, -1, -1 };
  return &_EsGobJmulticardCardDnieDnie3Cwa14890Constants_1;
}

@end


#line 66
void EsGobJmulticardCardDnieDnie3Cwa14890Constants_1_init(EsGobJmulticardCardDnieDnie3Cwa14890Constants_1 *self) {
  NSObject_init(self);
  self->encoded_ = [IOSByteArray newArrayWithBytes:(jbyte[]){
#line 71
    (jbyte) (jint) 0x30, (jbyte) (jint) 0x81, (jbyte) (jint) 0x9F, (jbyte) (jint) 0x30, (jbyte) (jint) 0x0D, (jbyte) (jint) 0x06, (jbyte) (jint) 0x09, (jbyte) (jint) 0x2A, (jbyte) (jint) 0x86, (jbyte) (jint) 0x48,
#line 72
    (jbyte) (jint) 0x86, (jbyte) (jint) 0xF7, (jbyte) (jint) 0x0D, (jbyte) (jint) 0x01, (jbyte) (jint) 0x01, (jbyte) (jint) 0x01, (jbyte) (jint) 0x05, (jbyte) (jint) 0x00, (jbyte) (jint) 0x03, (jbyte) (jint) 0x81,
#line 73
    (jbyte) (jint) 0x8D, (jbyte) (jint) 0x00, (jbyte) (jint) 0x30, (jbyte) (jint) 0x81, (jbyte) (jint) 0x89, (jbyte) (jint) 0x02, (jbyte) (jint) 0x81, (jbyte) (jint) 0x81, (jbyte) (jint) 0x00, (jbyte) (jint) 0xEA,
#line 74
    (jbyte) (jint) 0xDE, (jbyte) (jint) 0xDA, (jbyte) (jint) 0x45, (jbyte) (jint) 0x53, (jbyte) (jint) 0x32, (jbyte) (jint) 0x94, (jbyte) (jint) 0x50, (jbyte) (jint) 0x39, (jbyte) (jint) 0xDA, (jbyte) (jint) 0xA4,
#line 75
    (jbyte) (jint) 0x04, (jbyte) (jint) 0xC8, (jbyte) (jint) 0xEB, (jbyte) (jint) 0xC4, (jbyte) (jint) 0xD3, (jbyte) (jint) 0xB7, (jbyte) (jint) 0xF5, (jbyte) (jint) 0xDC, (jbyte) (jint) 0x86, (jbyte) (jint) 0x92,
#line 76
    (jbyte) (jint) 0x83, (jbyte) (jint) 0xCD, (jbyte) (jint) 0xEA, (jbyte) (jint) 0x2F, (jbyte) (jint) 0x10, (jbyte) (jint) 0x1E, (jbyte) (jint) 0x2A, (jbyte) (jint) 0xB5, (jbyte) (jint) 0x4F, (jbyte) (jint) 0xB0,
#line 77
    (jbyte) (jint) 0xD0, (jbyte) (jint) 0xB0, (jbyte) (jint) 0x3D, (jbyte) (jint) 0x8F, (jbyte) (jint) 0x03, (jbyte) (jint) 0x0D, (jbyte) (jint) 0xAF, (jbyte) (jint) 0x24, (jbyte) (jint) 0x58, (jbyte) (jint) 0x02,
#line 78
    (jbyte) (jint) 0x82, (jbyte) (jint) 0x88, (jbyte) (jint) 0xF5, (jbyte) (jint) 0x4C, (jbyte) (jint) 0xE5, (jbyte) (jint) 0x52, (jbyte) (jint) 0xF8, (jbyte) (jint) 0xFA, (jbyte) (jint) 0x57, (jbyte) (jint) 0xAB,
#line 79
    (jbyte) (jint) 0x2F, (jbyte) (jint) 0xB1, (jbyte) (jint) 0x03, (jbyte) (jint) 0xB1, (jbyte) (jint) 0x12, (jbyte) (jint) 0x42, (jbyte) (jint) 0x7E, (jbyte) (jint) 0x11, (jbyte) (jint) 0x13, (jbyte) (jint) 0x1D,
#line 80
    (jbyte) (jint) 0x1D, (jbyte) (jint) 0x27, (jbyte) (jint) 0xE1, (jbyte) (jint) 0x0A, (jbyte) (jint) 0x5B, (jbyte) (jint) 0x50, (jbyte) (jint) 0x0E, (jbyte) (jint) 0xAA, (jbyte) (jint) 0xE5, (jbyte) (jint) 0xD9,
#line 81
    (jbyte) (jint) 0x40, (jbyte) (jint) 0x30, (jbyte) (jint) 0x1E, (jbyte) (jint) 0x30, (jbyte) (jint) 0xEB, (jbyte) (jint) 0x26, (jbyte) (jint) 0xC3, (jbyte) (jint) 0xE9, (jbyte) (jint) 0x06, (jbyte) (jint) 0x6B,
#line 82
    (jbyte) (jint) 0x25, (jbyte) (jint) 0x71, (jbyte) (jint) 0x56, (jbyte) (jint) 0xED, (jbyte) (jint) 0x63, (jbyte) (jint) 0x9D, (jbyte) (jint) 0x70, (jbyte) (jint) 0xCC, (jbyte) (jint) 0xC0, (jbyte) (jint) 0x90,
#line 83
    (jbyte) (jint) 0xB8, (jbyte) (jint) 0x63, (jbyte) (jint) 0xAF, (jbyte) (jint) 0xBB, (jbyte) (jint) 0x3B, (jbyte) (jint) 0xFE, (jbyte) (jint) 0xD8, (jbyte) (jint) 0xC1, (jbyte) (jint) 0x7B, (jbyte) (jint) 0xE7,
#line 84
    (jbyte) (jint) 0x67, (jbyte) (jint) 0x30, (jbyte) (jint) 0x34, (jbyte) (jint) 0xB9, (jbyte) (jint) 0x82, (jbyte) (jint) 0x3E, (jbyte) (jint) 0x97, (jbyte) (jint) 0x7E, (jbyte) (jint) 0xD6, (jbyte) (jint) 0x57,
#line 85
    (jbyte) (jint) 0x25, (jbyte) (jint) 0x29, (jbyte) (jint) 0x27, (jbyte) (jint) 0xF9, (jbyte) (jint) 0x57, (jbyte) (jint) 0x5B, (jbyte) (jint) 0x9F, (jbyte) (jint) 0xFF, (jbyte) (jint) 0x66, (jbyte) (jint) 0x91,
#line 86
    (jbyte) (jint) 0xDB, (jbyte) (jint) 0x64, (jbyte) (jint) 0xF8, (jbyte) (jint) 0x0B, (jbyte) (jint) 0x5E, (jbyte) (jint) 0x92, (jbyte) (jint) 0xCD, (jbyte) (jint) 0x02, (jbyte) (jint) 0x03, (jbyte) (jint) 0x01,
#line 87
    (jbyte) (jint) 0x00, (jbyte) (jint) 0x01 } count:162];
  }


#line 66
EsGobJmulticardCardDnieDnie3Cwa14890Constants_1 *new_EsGobJmulticardCardDnieDnie3Cwa14890Constants_1_init() {
  J2OBJC_NEW_IMPL(EsGobJmulticardCardDnieDnie3Cwa14890Constants_1, init)
}


#line 66
EsGobJmulticardCardDnieDnie3Cwa14890Constants_1 *create_EsGobJmulticardCardDnieDnie3Cwa14890Constants_1_init() {
  J2OBJC_CREATE_IMPL(EsGobJmulticardCardDnieDnie3Cwa14890Constants_1, init)
}
