//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/com/aowagie/text/pdf/draw/DrawInterface.java
//

#include "J2ObjC_source.h"
#include "com/aowagie/text/pdf/draw/DrawInterface.h"

#if !__has_feature(objc_arc)
#error "com/aowagie/text/pdf/draw/DrawInterface must be compiled with ARC (-fobjc-arc)"
#endif

@interface ComAowagieTextPdfDrawDrawInterface : NSObject

@end

#line 1 "/Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/com/aowagie/text/pdf/draw/DrawInterface.java"


#line 60
@implementation ComAowagieTextPdfDrawDrawInterface

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(drawWithComAowagieTextPdfPdfContentByte:withFloat:withFloat:withFloat:withFloat:withFloat:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "draw", "LComAowagieTextPdfPdfContentByte;FFFFF" };
  static const J2ObjcClassInfo _ComAowagieTextPdfDrawDrawInterface = { "DrawInterface", "com.aowagie.text.pdf.draw", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_ComAowagieTextPdfDrawDrawInterface;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComAowagieTextPdfDrawDrawInterface)
