//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/org/bouncycastle/pqc/math/ntru/euclid/IntEuclidean.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgBouncycastlePqcMathNtruEuclidIntEuclidean")
#ifdef RESTRICT_OrgBouncycastlePqcMathNtruEuclidIntEuclidean
#define INCLUDE_ALL_OrgBouncycastlePqcMathNtruEuclidIntEuclidean 0
#else
#define INCLUDE_ALL_OrgBouncycastlePqcMathNtruEuclidIntEuclidean 1
#endif
#undef RESTRICT_OrgBouncycastlePqcMathNtruEuclidIntEuclidean

#if !defined (OrgBouncycastlePqcMathNtruEuclidIntEuclidean_) && (INCLUDE_ALL_OrgBouncycastlePqcMathNtruEuclidIntEuclidean || defined(INCLUDE_OrgBouncycastlePqcMathNtruEuclidIntEuclidean))
#define OrgBouncycastlePqcMathNtruEuclidIntEuclidean_

/*!
 @brief Extended Euclidean Algorithm in <code>int</code>s
 */
@interface OrgBouncycastlePqcMathNtruEuclidIntEuclidean : NSObject {
 @public
  jint x_;
  jint y_;
  jint gcd_;
}

#pragma mark Public

/*!
 @brief Runs the EEA on two <code>int</code>s<br>
  Implemented from pseudocode on <a href="https://en.wikipedia.org/wiki/Extended_Euclidean_algorithm">Wikipedia</a>.
 @param a
 @param b
 @return a <code>IntEuclidean</code> object that contains the result in the variables <code>x</code>, <code>y</code>, and <code>gcd</code>
 */
+ (OrgBouncycastlePqcMathNtruEuclidIntEuclidean *)calculateWithInt:(jint)a
                                                           withInt:(jint)b;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastlePqcMathNtruEuclidIntEuclidean)

FOUNDATION_EXPORT OrgBouncycastlePqcMathNtruEuclidIntEuclidean *OrgBouncycastlePqcMathNtruEuclidIntEuclidean_calculateWithInt_withInt_(jint a, jint b);

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastlePqcMathNtruEuclidIntEuclidean)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgBouncycastlePqcMathNtruEuclidIntEuclidean")
