//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/com/aowagie/text/RtfElementInterface.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAowagieTextRtfElementInterface")
#ifdef RESTRICT_ComAowagieTextRtfElementInterface
#define INCLUDE_ALL_ComAowagieTextRtfElementInterface 0
#else
#define INCLUDE_ALL_ComAowagieTextRtfElementInterface 1
#endif
#undef RESTRICT_ComAowagieTextRtfElementInterface

#if !defined (ComAowagieTextRtfElementInterface_) && (INCLUDE_ALL_ComAowagieTextRtfElementInterface || defined(INCLUDE_ComAowagieTextRtfElementInterface))
#define ComAowagieTextRtfElementInterface_

/*!
 @brief The RTF jar depends on the iText jar, but the iText jar may not
  depend on the RTF jar.This interface offers a temporary solution
  until we find a more elegant way to solve this.
 @since 2.1.0
 */
@protocol ComAowagieTextRtfElementInterface < JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(ComAowagieTextRtfElementInterface)

J2OBJC_TYPE_LITERAL_HEADER(ComAowagieTextRtfElementInterface)

#endif

#pragma pop_macro("INCLUDE_ALL_ComAowagieTextRtfElementInterface")
