//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/org/spongycastle/cms/CMSAttributeTableGenerator.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgSpongycastleCmsCMSAttributeTableGenerator")
#ifdef RESTRICT_OrgSpongycastleCmsCMSAttributeTableGenerator
#define INCLUDE_ALL_OrgSpongycastleCmsCMSAttributeTableGenerator 0
#else
#define INCLUDE_ALL_OrgSpongycastleCmsCMSAttributeTableGenerator 1
#endif
#undef RESTRICT_OrgSpongycastleCmsCMSAttributeTableGenerator

#if !defined (OrgSpongycastleCmsCMSAttributeTableGenerator_) && (INCLUDE_ALL_OrgSpongycastleCmsCMSAttributeTableGenerator || defined(INCLUDE_OrgSpongycastleCmsCMSAttributeTableGenerator))
#define OrgSpongycastleCmsCMSAttributeTableGenerator_

@class OrgSpongycastleAsn1CmsAttributeTable;
@protocol JavaUtilMap;

/*!
 @brief Note: The SIGNATURE parameter is only available when generating unsigned attributes.
 */
@protocol OrgSpongycastleCmsCMSAttributeTableGenerator < JavaObject >

- (OrgSpongycastleAsn1CmsAttributeTable *)getAttributesWithJavaUtilMap:(id<JavaUtilMap>)parameters;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgSpongycastleCmsCMSAttributeTableGenerator)

inline NSString *OrgSpongycastleCmsCMSAttributeTableGenerator_get_CONTENT_TYPE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgSpongycastleCmsCMSAttributeTableGenerator_CONTENT_TYPE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgSpongycastleCmsCMSAttributeTableGenerator, CONTENT_TYPE, NSString *)

inline NSString *OrgSpongycastleCmsCMSAttributeTableGenerator_get_DIGEST(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgSpongycastleCmsCMSAttributeTableGenerator_DIGEST;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgSpongycastleCmsCMSAttributeTableGenerator, DIGEST, NSString *)

inline NSString *OrgSpongycastleCmsCMSAttributeTableGenerator_get_SIGNATURE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgSpongycastleCmsCMSAttributeTableGenerator_SIGNATURE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgSpongycastleCmsCMSAttributeTableGenerator, SIGNATURE, NSString *)

inline NSString *OrgSpongycastleCmsCMSAttributeTableGenerator_get_DIGEST_ALGORITHM_IDENTIFIER(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgSpongycastleCmsCMSAttributeTableGenerator_DIGEST_ALGORITHM_IDENTIFIER;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgSpongycastleCmsCMSAttributeTableGenerator, DIGEST_ALGORITHM_IDENTIFIER, NSString *)

inline NSString *OrgSpongycastleCmsCMSAttributeTableGenerator_get_MAC_ALGORITHM_IDENTIFIER(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgSpongycastleCmsCMSAttributeTableGenerator_MAC_ALGORITHM_IDENTIFIER;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgSpongycastleCmsCMSAttributeTableGenerator, MAC_ALGORITHM_IDENTIFIER, NSString *)

inline NSString *OrgSpongycastleCmsCMSAttributeTableGenerator_get_SIGNATURE_ALGORITHM_IDENTIFIER(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgSpongycastleCmsCMSAttributeTableGenerator_SIGNATURE_ALGORITHM_IDENTIFIER;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgSpongycastleCmsCMSAttributeTableGenerator, SIGNATURE_ALGORITHM_IDENTIFIER, NSString *)

J2OBJC_TYPE_LITERAL_HEADER(OrgSpongycastleCmsCMSAttributeTableGenerator)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgSpongycastleCmsCMSAttributeTableGenerator")
