//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/jmulticard-ios/src/org/bouncycastle/pqc/math/ntru/polynomial/ModularResultant.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgBouncycastlePqcMathNtruPolynomialModularResultant")
#ifdef RESTRICT_OrgBouncycastlePqcMathNtruPolynomialModularResultant
#define INCLUDE_ALL_OrgBouncycastlePqcMathNtruPolynomialModularResultant 0
#else
#define INCLUDE_ALL_OrgBouncycastlePqcMathNtruPolynomialModularResultant 1
#endif
#undef RESTRICT_OrgBouncycastlePqcMathNtruPolynomialModularResultant

#if !defined (OrgBouncycastlePqcMathNtruPolynomialModularResultant_) && (INCLUDE_ALL_OrgBouncycastlePqcMathNtruPolynomialModularResultant || defined(INCLUDE_OrgBouncycastlePqcMathNtruPolynomialModularResultant))
#define OrgBouncycastlePqcMathNtruPolynomialModularResultant_

#define RESTRICT_OrgBouncycastlePqcMathNtruPolynomialResultant 1
#define INCLUDE_OrgBouncycastlePqcMathNtruPolynomialResultant 1
#include "org/bouncycastle/pqc/math/ntru/polynomial/Resultant.h"

@class JavaMathBigInteger;
@class OrgBouncycastlePqcMathNtruPolynomialBigIntPolynomial;

/*!
 @brief A resultant modulo a <code>BigInteger</code>
 */
@interface OrgBouncycastlePqcMathNtruPolynomialModularResultant : OrgBouncycastlePqcMathNtruPolynomialResultant {
 @public
  JavaMathBigInteger *modulus_;
}

#pragma mark Package-Private

- (instancetype)initWithOrgBouncycastlePqcMathNtruPolynomialBigIntPolynomial:(OrgBouncycastlePqcMathNtruPolynomialBigIntPolynomial *)rho
                                                      withJavaMathBigInteger:(JavaMathBigInteger *)res
                                                      withJavaMathBigInteger:(JavaMathBigInteger *)modulus;

/*!
 @brief Calculates a <code>rho</code> modulo <code>m1*m2</code> from
  two resultants whose <code>rho</code>s are modulo <code>m1</code> and <code>m2</code>.
 <br>
  </code>res</code> is set to <code>null</code>.
 @param modRes1
 @param modRes2
 @return <code>rho</code> modulo <code>modRes1.modulus * modRes2.modulus</code>, and <code>null</code> for </code>res</code>.
 */
+ (OrgBouncycastlePqcMathNtruPolynomialModularResultant *)combineRhoWithOrgBouncycastlePqcMathNtruPolynomialModularResultant:(OrgBouncycastlePqcMathNtruPolynomialModularResultant *)modRes1
                                                                    withOrgBouncycastlePqcMathNtruPolynomialModularResultant:(OrgBouncycastlePqcMathNtruPolynomialModularResultant *)modRes2;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithOrgBouncycastlePqcMathNtruPolynomialBigIntPolynomial:(OrgBouncycastlePqcMathNtruPolynomialBigIntPolynomial *)arg0
                                                      withJavaMathBigInteger:(JavaMathBigInteger *)arg1 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastlePqcMathNtruPolynomialModularResultant)

J2OBJC_FIELD_SETTER(OrgBouncycastlePqcMathNtruPolynomialModularResultant, modulus_, JavaMathBigInteger *)

FOUNDATION_EXPORT void OrgBouncycastlePqcMathNtruPolynomialModularResultant_initWithOrgBouncycastlePqcMathNtruPolynomialBigIntPolynomial_withJavaMathBigInteger_withJavaMathBigInteger_(OrgBouncycastlePqcMathNtruPolynomialModularResultant *self, OrgBouncycastlePqcMathNtruPolynomialBigIntPolynomial *rho, JavaMathBigInteger *res, JavaMathBigInteger *modulus);

FOUNDATION_EXPORT OrgBouncycastlePqcMathNtruPolynomialModularResultant *new_OrgBouncycastlePqcMathNtruPolynomialModularResultant_initWithOrgBouncycastlePqcMathNtruPolynomialBigIntPolynomial_withJavaMathBigInteger_withJavaMathBigInteger_(OrgBouncycastlePqcMathNtruPolynomialBigIntPolynomial *rho, JavaMathBigInteger *res, JavaMathBigInteger *modulus) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgBouncycastlePqcMathNtruPolynomialModularResultant *create_OrgBouncycastlePqcMathNtruPolynomialModularResultant_initWithOrgBouncycastlePqcMathNtruPolynomialBigIntPolynomial_withJavaMathBigInteger_withJavaMathBigInteger_(OrgBouncycastlePqcMathNtruPolynomialBigIntPolynomial *rho, JavaMathBigInteger *res, JavaMathBigInteger *modulus);

FOUNDATION_EXPORT OrgBouncycastlePqcMathNtruPolynomialModularResultant *OrgBouncycastlePqcMathNtruPolynomialModularResultant_combineRhoWithOrgBouncycastlePqcMathNtruPolynomialModularResultant_withOrgBouncycastlePqcMathNtruPolynomialModularResultant_(OrgBouncycastlePqcMathNtruPolynomialModularResultant *modRes1, OrgBouncycastlePqcMathNtruPolynomialModularResultant *modRes2);

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastlePqcMathNtruPolynomialModularResultant)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgBouncycastlePqcMathNtruPolynomialModularResultant")
