//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/org/bouncycastle/pqc/crypto/lms/LMSException.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgBouncycastlePqcCryptoLmsLMSException")
#ifdef RESTRICT_OrgBouncycastlePqcCryptoLmsLMSException
#define INCLUDE_ALL_OrgBouncycastlePqcCryptoLmsLMSException 0
#else
#define INCLUDE_ALL_OrgBouncycastlePqcCryptoLmsLMSException 1
#endif
#undef RESTRICT_OrgBouncycastlePqcCryptoLmsLMSException

#if !defined (OrgBouncycastlePqcCryptoLmsLMSException_) && (INCLUDE_ALL_OrgBouncycastlePqcCryptoLmsLMSException || defined(INCLUDE_OrgBouncycastlePqcCryptoLmsLMSException))
#define OrgBouncycastlePqcCryptoLmsLMSException_

#define RESTRICT_JavaLangException 1
#define INCLUDE_JavaLangException 1
#include "java/lang/Exception.h"

@class JavaLangThrowable;

@interface OrgBouncycastlePqcCryptoLmsLMSException : JavaLangException

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)message;

- (instancetype)initWithNSString:(NSString *)message
           withJavaLangThrowable:(JavaLangThrowable *)cause;

- (instancetype)initWithNSString:(NSString *)message
           withJavaLangThrowable:(JavaLangThrowable *)cause
                     withBoolean:(jboolean)enableSuppression
                     withBoolean:(jboolean)writableStackTrace;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)cause;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastlePqcCryptoLmsLMSException)

FOUNDATION_EXPORT void OrgBouncycastlePqcCryptoLmsLMSException_init(OrgBouncycastlePqcCryptoLmsLMSException *self);

FOUNDATION_EXPORT OrgBouncycastlePqcCryptoLmsLMSException *new_OrgBouncycastlePqcCryptoLmsLMSException_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgBouncycastlePqcCryptoLmsLMSException *create_OrgBouncycastlePqcCryptoLmsLMSException_init(void);

FOUNDATION_EXPORT void OrgBouncycastlePqcCryptoLmsLMSException_initWithNSString_(OrgBouncycastlePqcCryptoLmsLMSException *self, NSString *message);

FOUNDATION_EXPORT OrgBouncycastlePqcCryptoLmsLMSException *new_OrgBouncycastlePqcCryptoLmsLMSException_initWithNSString_(NSString *message) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgBouncycastlePqcCryptoLmsLMSException *create_OrgBouncycastlePqcCryptoLmsLMSException_initWithNSString_(NSString *message);

FOUNDATION_EXPORT void OrgBouncycastlePqcCryptoLmsLMSException_initWithNSString_withJavaLangThrowable_(OrgBouncycastlePqcCryptoLmsLMSException *self, NSString *message, JavaLangThrowable *cause);

FOUNDATION_EXPORT OrgBouncycastlePqcCryptoLmsLMSException *new_OrgBouncycastlePqcCryptoLmsLMSException_initWithNSString_withJavaLangThrowable_(NSString *message, JavaLangThrowable *cause) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgBouncycastlePqcCryptoLmsLMSException *create_OrgBouncycastlePqcCryptoLmsLMSException_initWithNSString_withJavaLangThrowable_(NSString *message, JavaLangThrowable *cause);

FOUNDATION_EXPORT void OrgBouncycastlePqcCryptoLmsLMSException_initWithJavaLangThrowable_(OrgBouncycastlePqcCryptoLmsLMSException *self, JavaLangThrowable *cause);

FOUNDATION_EXPORT OrgBouncycastlePqcCryptoLmsLMSException *new_OrgBouncycastlePqcCryptoLmsLMSException_initWithJavaLangThrowable_(JavaLangThrowable *cause) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgBouncycastlePqcCryptoLmsLMSException *create_OrgBouncycastlePqcCryptoLmsLMSException_initWithJavaLangThrowable_(JavaLangThrowable *cause);

FOUNDATION_EXPORT void OrgBouncycastlePqcCryptoLmsLMSException_initWithNSString_withJavaLangThrowable_withBoolean_withBoolean_(OrgBouncycastlePqcCryptoLmsLMSException *self, NSString *message, JavaLangThrowable *cause, jboolean enableSuppression, jboolean writableStackTrace);

FOUNDATION_EXPORT OrgBouncycastlePqcCryptoLmsLMSException *new_OrgBouncycastlePqcCryptoLmsLMSException_initWithNSString_withJavaLangThrowable_withBoolean_withBoolean_(NSString *message, JavaLangThrowable *cause, jboolean enableSuppression, jboolean writableStackTrace) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgBouncycastlePqcCryptoLmsLMSException *create_OrgBouncycastlePqcCryptoLmsLMSException_initWithNSString_withJavaLangThrowable_withBoolean_withBoolean_(NSString *message, JavaLangThrowable *cause, jboolean enableSuppression, jboolean writableStackTrace);

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastlePqcCryptoLmsLMSException)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgBouncycastlePqcCryptoLmsLMSException")
