//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/org/bouncycastle/math/ec/AbstractECMultiplier.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgBouncycastleMathEcAbstractECMultiplier")
#ifdef RESTRICT_OrgBouncycastleMathEcAbstractECMultiplier
#define INCLUDE_ALL_OrgBouncycastleMathEcAbstractECMultiplier 0
#else
#define INCLUDE_ALL_OrgBouncycastleMathEcAbstractECMultiplier 1
#endif
#undef RESTRICT_OrgBouncycastleMathEcAbstractECMultiplier

#if !defined (OrgBouncycastleMathEcAbstractECMultiplier_) && (INCLUDE_ALL_OrgBouncycastleMathEcAbstractECMultiplier || defined(INCLUDE_OrgBouncycastleMathEcAbstractECMultiplier))
#define OrgBouncycastleMathEcAbstractECMultiplier_

#define RESTRICT_OrgBouncycastleMathEcECMultiplier 1
#define INCLUDE_OrgBouncycastleMathEcECMultiplier 1
#include "org/bouncycastle/math/ec/ECMultiplier.h"

@class JavaMathBigInteger;
@class OrgBouncycastleMathEcECPoint;

@interface OrgBouncycastleMathEcAbstractECMultiplier : NSObject < OrgBouncycastleMathEcECMultiplier >

#pragma mark Public

- (instancetype)init;

- (OrgBouncycastleMathEcECPoint *)multiplyWithOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)p
                                                    withJavaMathBigInteger:(JavaMathBigInteger *)k;

#pragma mark Protected

- (OrgBouncycastleMathEcECPoint *)checkResultWithOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)p;

- (OrgBouncycastleMathEcECPoint *)multiplyPositiveWithOrgBouncycastleMathEcECPoint:(OrgBouncycastleMathEcECPoint *)p
                                                            withJavaMathBigInteger:(JavaMathBigInteger *)k;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleMathEcAbstractECMultiplier)

FOUNDATION_EXPORT void OrgBouncycastleMathEcAbstractECMultiplier_init(OrgBouncycastleMathEcAbstractECMultiplier *self);

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleMathEcAbstractECMultiplier)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgBouncycastleMathEcAbstractECMultiplier")
