//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/org/bouncycastle/asn1/DERUTF8String.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgBouncycastleAsn1DERUTF8String")
#ifdef RESTRICT_OrgBouncycastleAsn1DERUTF8String
#define INCLUDE_ALL_OrgBouncycastleAsn1DERUTF8String 0
#else
#define INCLUDE_ALL_OrgBouncycastleAsn1DERUTF8String 1
#endif
#undef RESTRICT_OrgBouncycastleAsn1DERUTF8String

#if !defined (OrgBouncycastleAsn1DERUTF8String_) && (INCLUDE_ALL_OrgBouncycastleAsn1DERUTF8String || defined(INCLUDE_OrgBouncycastleAsn1DERUTF8String))
#define OrgBouncycastleAsn1DERUTF8String_

#define RESTRICT_OrgBouncycastleAsn1ASN1UTF8String 1
#define INCLUDE_OrgBouncycastleAsn1ASN1UTF8String 1
#include "org/bouncycastle/asn1/ASN1UTF8String.h"

@class IOSByteArray;
@class OrgBouncycastleAsn1ASN1TaggedObject;

/*!
 @brief DER UTF8String object.
 */
@interface OrgBouncycastleAsn1DERUTF8String : OrgBouncycastleAsn1ASN1UTF8String

#pragma mark Public

/*!
 @brief Basic constructor
 @param string the string to be carried in the UTF8String object,
 */
- (instancetype)initWithNSString:(NSString *)string;

/*!
 @brief Return an UTF8 String from a tagged object.
 @param obj the tagged object holding the object we want
 @param explicit_ true if the object is meant to be explicitly tagged false                  otherwise.
 @throw IllegalArgumentExceptionif the tagged object cannot be converted.
 @return a DERUTF8String instance, or null
 */
+ (OrgBouncycastleAsn1DERUTF8String *)getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject:(OrgBouncycastleAsn1ASN1TaggedObject *)obj
                                                                             withBoolean:(jboolean)explicit_;

/*!
 @brief Return an UTF8 string from the passed in object.
 @param obj a DERUTF8String or an object that can be converted into one.
 @throw IllegalArgumentException
 if the object cannot be converted.
 @return a DERUTF8String instance, or null
 */
+ (OrgBouncycastleAsn1DERUTF8String *)getInstanceWithId:(id)obj;

#pragma mark Package-Private

- (instancetype)initWithByteArray:(IOSByteArray *)contents
                      withBoolean:(jboolean)clone;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleAsn1DERUTF8String)

FOUNDATION_EXPORT OrgBouncycastleAsn1DERUTF8String *OrgBouncycastleAsn1DERUTF8String_getInstanceWithId_(id obj);

FOUNDATION_EXPORT OrgBouncycastleAsn1DERUTF8String *OrgBouncycastleAsn1DERUTF8String_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_(OrgBouncycastleAsn1ASN1TaggedObject *obj, jboolean explicit_);

FOUNDATION_EXPORT void OrgBouncycastleAsn1DERUTF8String_initWithNSString_(OrgBouncycastleAsn1DERUTF8String *self, NSString *string);

FOUNDATION_EXPORT OrgBouncycastleAsn1DERUTF8String *new_OrgBouncycastleAsn1DERUTF8String_initWithNSString_(NSString *string) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgBouncycastleAsn1DERUTF8String *create_OrgBouncycastleAsn1DERUTF8String_initWithNSString_(NSString *string);

FOUNDATION_EXPORT void OrgBouncycastleAsn1DERUTF8String_initWithByteArray_withBoolean_(OrgBouncycastleAsn1DERUTF8String *self, IOSByteArray *contents, jboolean clone);

FOUNDATION_EXPORT OrgBouncycastleAsn1DERUTF8String *new_OrgBouncycastleAsn1DERUTF8String_initWithByteArray_withBoolean_(IOSByteArray *contents, jboolean clone) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgBouncycastleAsn1DERUTF8String *create_OrgBouncycastleAsn1DERUTF8String_initWithByteArray_withBoolean_(IOSByteArray *contents, jboolean clone);

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleAsn1DERUTF8String)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgBouncycastleAsn1DERUTF8String")
