//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/org/spongycastle/asn1/cryptopro/GostR3410TransportParameters.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgSpongycastleAsn1CryptoproGostR3410TransportParameters")
#ifdef RESTRICT_OrgSpongycastleAsn1CryptoproGostR3410TransportParameters
#define INCLUDE_ALL_OrgSpongycastleAsn1CryptoproGostR3410TransportParameters 0
#else
#define INCLUDE_ALL_OrgSpongycastleAsn1CryptoproGostR3410TransportParameters 1
#endif
#undef RESTRICT_OrgSpongycastleAsn1CryptoproGostR3410TransportParameters

#if !defined (OrgSpongycastleAsn1CryptoproGostR3410TransportParameters_) && (INCLUDE_ALL_OrgSpongycastleAsn1CryptoproGostR3410TransportParameters || defined(INCLUDE_OrgSpongycastleAsn1CryptoproGostR3410TransportParameters))
#define OrgSpongycastleAsn1CryptoproGostR3410TransportParameters_

#define RESTRICT_OrgSpongycastleAsn1ASN1Object 1
#define INCLUDE_OrgSpongycastleAsn1ASN1Object 1
#include "org/spongycastle/asn1/ASN1Object.h"

@class IOSByteArray;
@class OrgSpongycastleAsn1ASN1ObjectIdentifier;
@class OrgSpongycastleAsn1ASN1Primitive;
@class OrgSpongycastleAsn1ASN1TaggedObject;
@class OrgSpongycastleAsn1X509SubjectPublicKeyInfo;

/*!
 @brief @code

  GostR3410-TransportParameters ::= SEQUENCE {
         encryptionParamSet   OBJECT IDENTIFIER,
         ephemeralPublicKey   [0] IMPLICIT SubjectPublicKeyInfo OPTIONAL,
         ukm                  OCTET STRING
  }
  
@endcode
 */
@interface OrgSpongycastleAsn1CryptoproGostR3410TransportParameters : OrgSpongycastleAsn1ASN1Object

#pragma mark Public

- (instancetype)initWithOrgSpongycastleAsn1ASN1ObjectIdentifier:(OrgSpongycastleAsn1ASN1ObjectIdentifier *)encryptionParamSet
                withOrgSpongycastleAsn1X509SubjectPublicKeyInfo:(OrgSpongycastleAsn1X509SubjectPublicKeyInfo *)ephemeralPublicKey
                                                  withByteArray:(IOSByteArray *)ukm;

- (OrgSpongycastleAsn1ASN1ObjectIdentifier *)getEncryptionParamSet;

- (OrgSpongycastleAsn1X509SubjectPublicKeyInfo *)getEphemeralPublicKey;

+ (OrgSpongycastleAsn1CryptoproGostR3410TransportParameters *)getInstanceWithOrgSpongycastleAsn1ASN1TaggedObject:(OrgSpongycastleAsn1ASN1TaggedObject *)obj
                                                                                                     withBoolean:(jboolean)explicit_;

+ (OrgSpongycastleAsn1CryptoproGostR3410TransportParameters *)getInstanceWithId:(id)obj;

- (IOSByteArray *)getUkm;

- (OrgSpongycastleAsn1ASN1Primitive *)toASN1Primitive;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgSpongycastleAsn1CryptoproGostR3410TransportParameters)

FOUNDATION_EXPORT void OrgSpongycastleAsn1CryptoproGostR3410TransportParameters_initWithOrgSpongycastleAsn1ASN1ObjectIdentifier_withOrgSpongycastleAsn1X509SubjectPublicKeyInfo_withByteArray_(OrgSpongycastleAsn1CryptoproGostR3410TransportParameters *self, OrgSpongycastleAsn1ASN1ObjectIdentifier *encryptionParamSet, OrgSpongycastleAsn1X509SubjectPublicKeyInfo *ephemeralPublicKey, IOSByteArray *ukm);

FOUNDATION_EXPORT OrgSpongycastleAsn1CryptoproGostR3410TransportParameters *new_OrgSpongycastleAsn1CryptoproGostR3410TransportParameters_initWithOrgSpongycastleAsn1ASN1ObjectIdentifier_withOrgSpongycastleAsn1X509SubjectPublicKeyInfo_withByteArray_(OrgSpongycastleAsn1ASN1ObjectIdentifier *encryptionParamSet, OrgSpongycastleAsn1X509SubjectPublicKeyInfo *ephemeralPublicKey, IOSByteArray *ukm) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgSpongycastleAsn1CryptoproGostR3410TransportParameters *create_OrgSpongycastleAsn1CryptoproGostR3410TransportParameters_initWithOrgSpongycastleAsn1ASN1ObjectIdentifier_withOrgSpongycastleAsn1X509SubjectPublicKeyInfo_withByteArray_(OrgSpongycastleAsn1ASN1ObjectIdentifier *encryptionParamSet, OrgSpongycastleAsn1X509SubjectPublicKeyInfo *ephemeralPublicKey, IOSByteArray *ukm);

FOUNDATION_EXPORT OrgSpongycastleAsn1CryptoproGostR3410TransportParameters *OrgSpongycastleAsn1CryptoproGostR3410TransportParameters_getInstanceWithId_(id obj);

FOUNDATION_EXPORT OrgSpongycastleAsn1CryptoproGostR3410TransportParameters *OrgSpongycastleAsn1CryptoproGostR3410TransportParameters_getInstanceWithOrgSpongycastleAsn1ASN1TaggedObject_withBoolean_(OrgSpongycastleAsn1ASN1TaggedObject *obj, jboolean explicit_);

J2OBJC_TYPE_LITERAL_HEADER(OrgSpongycastleAsn1CryptoproGostR3410TransportParameters)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgSpongycastleAsn1CryptoproGostR3410TransportParameters")
