//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/org/bouncycastle/crypto/DerivationParameters.java
//

#include "J2ObjC_source.h"
#include "org/bouncycastle/crypto/DerivationParameters.h"

#if !__has_feature(objc_arc)
#error "org/bouncycastle/crypto/DerivationParameters must be compiled with ARC (-fobjc-arc)"
#endif

@interface OrgBouncycastleCryptoDerivationParameters : NSObject

@end

#line 1 "/Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/org/bouncycastle/crypto/DerivationParameters.java"


#line 6
@implementation OrgBouncycastleCryptoDerivationParameters

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcClassInfo _OrgBouncycastleCryptoDerivationParameters = { "DerivationParameters", "org.bouncycastle.crypto", NULL, NULL, NULL, 7, 0x609, 0, 0, -1, -1, -1, -1, -1 };
  return &_OrgBouncycastleCryptoDerivationParameters;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgBouncycastleCryptoDerivationParameters)
