//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/org/spongycastle/math/ec/PreCompInfo.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgSpongycastleMathEcPreCompInfo")
#ifdef RESTRICT_OrgSpongycastleMathEcPreCompInfo
#define INCLUDE_ALL_OrgSpongycastleMathEcPreCompInfo 0
#else
#define INCLUDE_ALL_OrgSpongycastleMathEcPreCompInfo 1
#endif
#undef RESTRICT_OrgSpongycastleMathEcPreCompInfo

#if !defined (OrgSpongycastleMathEcPreCompInfo_) && (INCLUDE_ALL_OrgSpongycastleMathEcPreCompInfo || defined(INCLUDE_OrgSpongycastleMathEcPreCompInfo))
#define OrgSpongycastleMathEcPreCompInfo_

/*!
 @brief Interface for classes storing precomputation data for multiplication
  algorithms.Used as a Memento (see GOF patterns) by e.g.
 <code>WNafL2RMultiplier</code>.
 */
@protocol OrgSpongycastleMathEcPreCompInfo < JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgSpongycastleMathEcPreCompInfo)

J2OBJC_TYPE_LITERAL_HEADER(OrgSpongycastleMathEcPreCompInfo)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgSpongycastleMathEcPreCompInfo")
