//
//  GlobalConstants.h
//  Cliente @firma
//
//  Created by Sergio PH on 27/08/2018.
//  Copyright © 2018 Atos. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface GlobalConstants : NSObject

FOUNDATION_EXPORT NSString *const URL_READED;
FOUNDATION_EXPORT NSString *const ANF_PF_ACTIVO;
FOUNDATION_EXPORT NSString *const PF_ACTIVO_FIR_SHA1;
FOUNDATION_EXPORT NSString *const PRUEBAS_PORTAFIRMAS;
FOUNDATION_EXPORT NSString *const INACTIVE;
FOUNDATION_EXPORT NSString *const URL;
FOUNDATION_EXPORT NSString *const IPAD;
FOUNDATION_EXPORT NSString *const IPAD_STORYBOARD;
FOUNDATION_EXPORT NSString *const IPHONE_STORYBOARD;
FOUNDATION_EXPORT NSString *const BACKGROUND;
FOUNDATION_EXPORT NSString *const PREFERENCE_SPECIFIERS;
FOUNDATION_EXPORT NSString *const KEY;
FOUNDATION_EXPORT NSString *const DEFAULT_VALUE;
FOUNDATION_EXPORT NSString *const DOCUMENTS;
FOUNDATION_EXPORT NSString *const OK;
FOUNDATION_EXPORT NSString *const POST;
FOUNDATION_EXPORT NSString *const BINARY;
FOUNDATION_EXPORT NSString *const PRE;
FOUNDATION_EXPORT NSString *const STRING_FALSE;
FOUNDATION_EXPORT NSString *const SERVER_URL;
FOUNDATION_EXPORT NSString *const SIGNATURES;
FOUNDATION_EXPORT NSString *const SIGNATURE;
FOUNDATION_EXPORT NSString *const PARAMETERS;
FOUNDATION_EXPORT NSString *const WITH;

@end
