//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/org/bouncycastle/pqc/jcajce/spec/LMSHSSParameterSpec.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Deprecated.h"
#include "java/lang/annotation/Annotation.h"
#include "org/bouncycastle/pqc/jcajce/spec/LMSHSSParameterSpec.h"

#if !__has_feature(objc_arc)
#error "org/bouncycastle/pqc/jcajce/spec/LMSHSSParameterSpec must be compiled with ARC (-fobjc-arc)"
#endif

@interface OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec () {
 @public
  IOSObjectArray *specs_;
}

@end

J2OBJC_FIELD_SETTER(OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec, specs_, IOSObjectArray *)

__attribute__((unused)) static IOSObjectArray *OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec__Annotations$0(void);

#line 1 "/Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/org/bouncycastle/pqc/jcajce/spec/LMSHSSParameterSpec.java"


#line 10
@implementation OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec


#line 20
- (instancetype)initWithOrgBouncycastlePqcJcajceSpecLMSParameterSpecArray:(IOSObjectArray *)specs {
  OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec_initWithOrgBouncycastlePqcJcajceSpecLMSParameterSpecArray_(self, specs);
  return self;
}


#line 30
- (IOSObjectArray *)getLMSSpecs {
  
#line 32
  return [((IOSObjectArray *) nil_chk(specs_)) java_clone];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "[LOrgBouncycastlePqcJcajceSpecLMSParameterSpec;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithOrgBouncycastlePqcJcajceSpecLMSParameterSpecArray:);
  methods[1].selector = @selector(getLMSSpecs);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "specs_", "[LOrgBouncycastlePqcJcajceSpecLMSParameterSpec;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "[LOrgBouncycastlePqcJcajceSpecLMSParameterSpec;", (void *)&OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec__Annotations$0 };
  static const J2ObjcClassInfo _OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec = { "LMSHSSParameterSpec", "org.bouncycastle.pqc.jcajce.spec", ptrTable, methods, fields, 7, 0x1, 2, 1, -1, -1, -1, -1, 1 };
  return &_OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec;
}

@end


#line 20
void OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec_initWithOrgBouncycastlePqcJcajceSpecLMSParameterSpecArray_(OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec *self, IOSObjectArray *specs) {
  NSObject_init(self);
  self->specs_ = [((IOSObjectArray *) nil_chk(specs)) java_clone];
}


#line 20
OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec *new_OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec_initWithOrgBouncycastlePqcJcajceSpecLMSParameterSpecArray_(IOSObjectArray *specs) {
  J2OBJC_NEW_IMPL(OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec, initWithOrgBouncycastlePqcJcajceSpecLMSParameterSpecArray_, specs)
}


#line 20
OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec *create_OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec_initWithOrgBouncycastlePqcJcajceSpecLMSParameterSpecArray_(IOSObjectArray *specs) {
  J2OBJC_CREATE_IMPL(OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec, initWithOrgBouncycastlePqcJcajceSpecLMSParameterSpecArray_, specs)
}

IOSObjectArray *OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec__Annotations$0() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaLangDeprecated() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgBouncycastlePqcJcajceSpecLMSHSSParameterSpec)
