//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/pades-ios-mini/src/main/java/es/gob/afirma/core/AGEPolicyIncompatibilityException.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AGEPolicyIncompatibilityException")
#ifdef RESTRICT_AGEPolicyIncompatibilityException
#define INCLUDE_ALL_AGEPolicyIncompatibilityException 0
#else
#define INCLUDE_ALL_AGEPolicyIncompatibilityException 1
#endif
#undef RESTRICT_AGEPolicyIncompatibilityException

#if !defined (EsGobAfirmaCoreAGEPolicyIncompatibilityException_) && (INCLUDE_ALL_AGEPolicyIncompatibilityException || defined(INCLUDE_EsGobAfirmaCoreAGEPolicyIncompatibilityException))
#define EsGobAfirmaCoreAGEPolicyIncompatibilityException_

#define RESTRICT_CustomRuntimeConfigNeededException 1
#define INCLUDE_EsGobAfirmaCoreCustomRuntimeConfigNeededException 1
#include "CustomRuntimeConfigNeededException.h"

@class EsGobAfirmaCoreRuntimeConfigNeededException_RequestType;
@class JavaLangThrowable;
@class JavaUtilProperties;

/*!
 @brief Excepci&oacute;n que denota que se va a generar una firma que declara la pol&iacute;tica de firma
  de la AGE, pero es incompatible con ella.
 */
@interface EsGobAfirmaCoreAGEPolicyIncompatibilityException : EsGobAfirmaCoreCustomRuntimeConfigNeededException

#pragma mark Public

/*!
 @brief Crear la excepci&oacute;n motivada por lo indicado en el mensaje.
 @param message Mensaje descriptivo del problema.
 */
- (instancetype)initWithNSString:(NSString *)message;

/*!
 @brief Crear la excepci&oacute;n motivada por lo indicado en el mensaje.
 @param message Mensaje descriptivo del problema.
 @param operation C &oacute; digo de operaci &oacute; n que identifica el mensaje de solicitud  de confirmaci &oacute; n al usuario.
 */
- (instancetype)initWithNSString:(NSString *)message
                         withInt:(jint)operation;

/*!
 @brief Crear la excepci&oacute;n motivada por lo indicado en el mensaje.
 @param message Mensaje descriptivo del problema.
 @param operation C &oacute; digo de operaci &oacute; n que identifica el mensaje de solicitud  de confirmaci &oacute; n al usuario.
 @param cause Origen del problema.
 */
- (instancetype)initWithNSString:(NSString *)message
                         withInt:(jint)operation
           withJavaLangThrowable:(JavaLangThrowable *)cause;

/*!
 @brief Crear la excepci&oacute;n motivada por lo indicado en el mensaje.
 @param message Mensaje descriptivo del problema.
 @param cause Origen del problema.
 */
- (instancetype)initWithNSString:(NSString *)message
           withJavaLangThrowable:(JavaLangThrowable *)cause;

- (void)prepareOperationWithConfirmationWithJavaUtilProperties:(JavaUtilProperties *)extraParams;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0
withEsGobAfirmaCoreRuntimeConfigNeededException_RequestType:(EsGobAfirmaCoreRuntimeConfigNeededException_RequestType *)arg1
                    withNSString:(NSString *)arg2
                    withNSString:(NSString *)arg3 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
withEsGobAfirmaCoreRuntimeConfigNeededException_RequestType:(EsGobAfirmaCoreRuntimeConfigNeededException_RequestType *)arg1
                    withNSString:(NSString *)arg2
                    withNSString:(NSString *)arg3
           withJavaLangThrowable:(JavaLangThrowable *)arg4 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(EsGobAfirmaCoreAGEPolicyIncompatibilityException)

inline NSString *EsGobAfirmaCoreAGEPolicyIncompatibilityException_get_REQUESTOR_SIGN_MSG_CODE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *EsGobAfirmaCoreAGEPolicyIncompatibilityException_REQUESTOR_SIGN_MSG_CODE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EsGobAfirmaCoreAGEPolicyIncompatibilityException, REQUESTOR_SIGN_MSG_CODE, NSString *)

inline NSString *EsGobAfirmaCoreAGEPolicyIncompatibilityException_get_REQUESTOR_COSIGN_MSG_CODE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *EsGobAfirmaCoreAGEPolicyIncompatibilityException_REQUESTOR_COSIGN_MSG_CODE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EsGobAfirmaCoreAGEPolicyIncompatibilityException, REQUESTOR_COSIGN_MSG_CODE, NSString *)

inline NSString *EsGobAfirmaCoreAGEPolicyIncompatibilityException_get_REQUESTOR_COUNTERSIGN_MSG_CODE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *EsGobAfirmaCoreAGEPolicyIncompatibilityException_REQUESTOR_COUNTERSIGN_MSG_CODE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(EsGobAfirmaCoreAGEPolicyIncompatibilityException, REQUESTOR_COUNTERSIGN_MSG_CODE, NSString *)

/*!
 @brief Error identificado durante una operaci&oacute;n de firma.
 */
inline jint EsGobAfirmaCoreAGEPolicyIncompatibilityException_get_OP_SIGN(void);
#define EsGobAfirmaCoreAGEPolicyIncompatibilityException_OP_SIGN 1
J2OBJC_STATIC_FIELD_CONSTANT(EsGobAfirmaCoreAGEPolicyIncompatibilityException, OP_SIGN, jint)

/*!
 @brief Error identificado durante una operaci&oacute;n de cofirma.
 */
inline jint EsGobAfirmaCoreAGEPolicyIncompatibilityException_get_OP_COSIGN(void);
#define EsGobAfirmaCoreAGEPolicyIncompatibilityException_OP_COSIGN 2
J2OBJC_STATIC_FIELD_CONSTANT(EsGobAfirmaCoreAGEPolicyIncompatibilityException, OP_COSIGN, jint)

/*!
 @brief Error identificado durante una operaci&oacute;n de contrafirma.
 */
inline jint EsGobAfirmaCoreAGEPolicyIncompatibilityException_get_OP_COUNTERSIGN(void);
#define EsGobAfirmaCoreAGEPolicyIncompatibilityException_OP_COUNTERSIGN 3
J2OBJC_STATIC_FIELD_CONSTANT(EsGobAfirmaCoreAGEPolicyIncompatibilityException, OP_COUNTERSIGN, jint)

FOUNDATION_EXPORT void EsGobAfirmaCoreAGEPolicyIncompatibilityException_initWithNSString_(EsGobAfirmaCoreAGEPolicyIncompatibilityException *self, NSString *message);

FOUNDATION_EXPORT EsGobAfirmaCoreAGEPolicyIncompatibilityException *new_EsGobAfirmaCoreAGEPolicyIncompatibilityException_initWithNSString_(NSString *message) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EsGobAfirmaCoreAGEPolicyIncompatibilityException *create_EsGobAfirmaCoreAGEPolicyIncompatibilityException_initWithNSString_(NSString *message);

FOUNDATION_EXPORT void EsGobAfirmaCoreAGEPolicyIncompatibilityException_initWithNSString_withInt_(EsGobAfirmaCoreAGEPolicyIncompatibilityException *self, NSString *message, jint operation);

FOUNDATION_EXPORT EsGobAfirmaCoreAGEPolicyIncompatibilityException *new_EsGobAfirmaCoreAGEPolicyIncompatibilityException_initWithNSString_withInt_(NSString *message, jint operation) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EsGobAfirmaCoreAGEPolicyIncompatibilityException *create_EsGobAfirmaCoreAGEPolicyIncompatibilityException_initWithNSString_withInt_(NSString *message, jint operation);

FOUNDATION_EXPORT void EsGobAfirmaCoreAGEPolicyIncompatibilityException_initWithNSString_withJavaLangThrowable_(EsGobAfirmaCoreAGEPolicyIncompatibilityException *self, NSString *message, JavaLangThrowable *cause);

FOUNDATION_EXPORT EsGobAfirmaCoreAGEPolicyIncompatibilityException *new_EsGobAfirmaCoreAGEPolicyIncompatibilityException_initWithNSString_withJavaLangThrowable_(NSString *message, JavaLangThrowable *cause) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EsGobAfirmaCoreAGEPolicyIncompatibilityException *create_EsGobAfirmaCoreAGEPolicyIncompatibilityException_initWithNSString_withJavaLangThrowable_(NSString *message, JavaLangThrowable *cause);

FOUNDATION_EXPORT void EsGobAfirmaCoreAGEPolicyIncompatibilityException_initWithNSString_withInt_withJavaLangThrowable_(EsGobAfirmaCoreAGEPolicyIncompatibilityException *self, NSString *message, jint operation, JavaLangThrowable *cause);

FOUNDATION_EXPORT EsGobAfirmaCoreAGEPolicyIncompatibilityException *new_EsGobAfirmaCoreAGEPolicyIncompatibilityException_initWithNSString_withInt_withJavaLangThrowable_(NSString *message, jint operation, JavaLangThrowable *cause) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EsGobAfirmaCoreAGEPolicyIncompatibilityException *create_EsGobAfirmaCoreAGEPolicyIncompatibilityException_initWithNSString_withInt_withJavaLangThrowable_(NSString *message, jint operation, JavaLangThrowable *cause);

J2OBJC_TYPE_LITERAL_HEADER(EsGobAfirmaCoreAGEPolicyIncompatibilityException)

#endif

#pragma pop_macro("INCLUDE_ALL_AGEPolicyIncompatibilityException")
