//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/org/spongycastle/asn1/ASN1OutputStream.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ASN1OutputStream")
#ifdef RESTRICT_ASN1OutputStream
#define INCLUDE_ALL_ASN1OutputStream 0
#else
#define INCLUDE_ALL_ASN1OutputStream 1
#endif
#undef RESTRICT_ASN1OutputStream

#if !defined (OrgSpongycastleAsn1ASN1OutputStream_) && (INCLUDE_ALL_ASN1OutputStream || defined(INCLUDE_OrgSpongycastleAsn1ASN1OutputStream))
#define OrgSpongycastleAsn1ASN1OutputStream_

@class IOSByteArray;
@class JavaIoOutputStream;
@class OrgSpongycastleAsn1ASN1Primitive;
@protocol OrgSpongycastleAsn1ASN1Encodable;

/*!
 @brief Stream that produces output based on the default encoding for the passed in objects.
 */
@interface OrgSpongycastleAsn1ASN1OutputStream : NSObject

#pragma mark Public

- (instancetype)initWithJavaIoOutputStream:(JavaIoOutputStream *)os;

- (void)close;

- (void)flush;

- (void)writeObjectWithOrgSpongycastleAsn1ASN1Encodable:(id<OrgSpongycastleAsn1ASN1Encodable>)obj;

#pragma mark Protected

- (void)writeNull;

#pragma mark Package-Private

- (OrgSpongycastleAsn1ASN1OutputStream *)getDERSubStream;

- (OrgSpongycastleAsn1ASN1OutputStream *)getDLSubStream;

- (void)writeWithByteArray:(IOSByteArray *)bytes;

- (void)writeWithByteArray:(IOSByteArray *)bytes
                   withInt:(jint)off
                   withInt:(jint)len;

- (void)writeWithInt:(jint)b;

- (void)writeEncodedWithInt:(jint)tag
              withByteArray:(IOSByteArray *)bytes;

- (void)writeEncodedWithInt:(jint)flags
                    withInt:(jint)tagNo
              withByteArray:(IOSByteArray *)bytes;

- (void)writeImplicitObjectWithOrgSpongycastleAsn1ASN1Primitive:(OrgSpongycastleAsn1ASN1Primitive *)obj;

- (void)writeLengthWithInt:(jint)length;

- (void)writeTagWithInt:(jint)flags
                withInt:(jint)tagNo;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgSpongycastleAsn1ASN1OutputStream)

FOUNDATION_EXPORT void OrgSpongycastleAsn1ASN1OutputStream_initWithJavaIoOutputStream_(OrgSpongycastleAsn1ASN1OutputStream *self, JavaIoOutputStream *os);

FOUNDATION_EXPORT OrgSpongycastleAsn1ASN1OutputStream *new_OrgSpongycastleAsn1ASN1OutputStream_initWithJavaIoOutputStream_(JavaIoOutputStream *os) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgSpongycastleAsn1ASN1OutputStream *create_OrgSpongycastleAsn1ASN1OutputStream_initWithJavaIoOutputStream_(JavaIoOutputStream *os);

J2OBJC_TYPE_LITERAL_HEADER(OrgSpongycastleAsn1ASN1OutputStream)

#endif

#pragma pop_macro("INCLUDE_ALL_ASN1OutputStream")
