//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/pades-ios-mini/src/main/java/org/spongycastle/asn1/BERTaggedObjectParser.java
//

#include "ASN1Encodable.h"
#include "ASN1ParsingException.h"
#include "ASN1Primitive.h"
#include "ASN1StreamParser.h"
#include "BERTaggedObjectParser.h"
#include "J2ObjC_source.h"
#include "java/io/IOException.h"

#if !__has_feature(objc_arc)
#error "BERTaggedObjectParser must be compiled with ARC (-fobjc-arc)"
#endif

@interface OrgSpongycastleAsn1BERTaggedObjectParser () {
 @public
  jboolean _constructed_;
  jint _tagNumber_;
  OrgSpongycastleAsn1ASN1StreamParser *_parser_;
}

@end

J2OBJC_FIELD_SETTER(OrgSpongycastleAsn1BERTaggedObjectParser, _parser_, OrgSpongycastleAsn1ASN1StreamParser *)

#line 1 "/Users/desarrolloabamobile/Downloads/pades-ios-mini/src/main/java/org/spongycastle/asn1/BERTaggedObjectParser.java"


#line 8
@implementation OrgSpongycastleAsn1BERTaggedObjectParser


#line 15
- (instancetype)initWithBoolean:(jboolean)constructed
                        withInt:(jint)tagNumber
withOrgSpongycastleAsn1ASN1StreamParser:(OrgSpongycastleAsn1ASN1StreamParser *)parser {
  OrgSpongycastleAsn1BERTaggedObjectParser_initWithBoolean_withInt_withOrgSpongycastleAsn1ASN1StreamParser_(self, constructed, tagNumber, parser);
  return self;
}


#line 30
- (jboolean)isConstructed {
  
#line 32
  return _constructed_;
}


#line 40
- (jint)getTagNo {
  
#line 42
  return _tagNumber_;
}


#line 53
- (id<OrgSpongycastleAsn1ASN1Encodable>)getObjectParserWithInt:(jint)tag
                                                   withBoolean:(jboolean)isExplicit {
  
#line 58
  if (isExplicit) {
    
#line 60
    if (!_constructed_) {
      
#line 62
      @throw new_JavaIoIOException_initWithNSString_(@"Explicit tags must be constructed (see X.690 8.14.2)");
    }
    return [((OrgSpongycastleAsn1ASN1StreamParser *) nil_chk(_parser_)) readObject];
  }
  
#line 67
  return [((OrgSpongycastleAsn1ASN1StreamParser *) nil_chk(_parser_)) readImplicitWithBoolean:_constructed_ withInt:tag];
}


#line 76
- (OrgSpongycastleAsn1ASN1Primitive *)getLoadedObject {
  
#line 79
  return [((OrgSpongycastleAsn1ASN1StreamParser *) nil_chk(_parser_)) readTaggedObjectWithBoolean:_constructed_ withInt:_tagNumber_];
}


#line 87
- (OrgSpongycastleAsn1ASN1Primitive *)toASN1Primitive {
  
#line 89
  @try {
    
#line 91
    return [self getLoadedObject];
  }
  @catch (JavaIoIOException *e) {
    
#line 95
    @throw new_OrgSpongycastleAsn1ASN1ParsingException_initWithNSString_([e getMessage]);
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgSpongycastleAsn1ASN1Encodable;", 0x1, 1, 2, 3, -1, -1, -1 },
    { NULL, "LOrgSpongycastleAsn1ASN1Primitive;", 0x1, -1, -1, 3, -1, -1, -1 },
    { NULL, "LOrgSpongycastleAsn1ASN1Primitive;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithBoolean:withInt:withOrgSpongycastleAsn1ASN1StreamParser:);
  methods[1].selector = @selector(isConstructed);
  methods[2].selector = @selector(getTagNo);
  methods[3].selector = @selector(getObjectParserWithInt:withBoolean:);
  methods[4].selector = @selector(getLoadedObject);
  methods[5].selector = @selector(toASN1Primitive);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "_constructed_", "Z", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "_tagNumber_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "_parser_", "LOrgSpongycastleAsn1ASN1StreamParser;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "ZILOrgSpongycastleAsn1ASN1StreamParser;", "getObjectParser", "IZ", "LJavaIoIOException;" };
  static const J2ObjcClassInfo _OrgSpongycastleAsn1BERTaggedObjectParser = { "BERTaggedObjectParser", "org.spongycastle.asn1", ptrTable, methods, fields, 7, 0x1, 6, 3, -1, -1, -1, -1, -1 };
  return &_OrgSpongycastleAsn1BERTaggedObjectParser;
}

@end


#line 15
void OrgSpongycastleAsn1BERTaggedObjectParser_initWithBoolean_withInt_withOrgSpongycastleAsn1ASN1StreamParser_(OrgSpongycastleAsn1BERTaggedObjectParser *self, jboolean constructed, jint tagNumber, OrgSpongycastleAsn1ASN1StreamParser *parser) {
  NSObject_init(self);
  
#line 20
  self->_constructed_ = constructed;
  self->_tagNumber_ = tagNumber;
  self->_parser_ = parser;
}


#line 15
OrgSpongycastleAsn1BERTaggedObjectParser *new_OrgSpongycastleAsn1BERTaggedObjectParser_initWithBoolean_withInt_withOrgSpongycastleAsn1ASN1StreamParser_(jboolean constructed, jint tagNumber, OrgSpongycastleAsn1ASN1StreamParser *parser) {
  J2OBJC_NEW_IMPL(OrgSpongycastleAsn1BERTaggedObjectParser, initWithBoolean_withInt_withOrgSpongycastleAsn1ASN1StreamParser_, constructed, tagNumber, parser)
}


#line 15
OrgSpongycastleAsn1BERTaggedObjectParser *create_OrgSpongycastleAsn1BERTaggedObjectParser_initWithBoolean_withInt_withOrgSpongycastleAsn1ASN1StreamParser_(jboolean constructed, jint tagNumber, OrgSpongycastleAsn1ASN1StreamParser *parser) {
  J2OBJC_CREATE_IMPL(OrgSpongycastleAsn1BERTaggedObjectParser, initWithBoolean_withInt_withOrgSpongycastleAsn1ASN1StreamParser_, constructed, tagNumber, parser)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgSpongycastleAsn1BERTaggedObjectParser)
