//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/pades-ios-mini/src/main/java/org/spongycastle/asn1/x509/CRLNumber.java
//

#include "ASN1Integer.h"
#include "ASN1Object.h"
#include "ASN1Primitive.h"
#include "CRLNumber.h"
#include "J2ObjC_source.h"
#include "java/math/BigInteger.h"

#if !__has_feature(objc_arc)
#error "CRLNumber must be compiled with ARC (-fobjc-arc)"
#endif

@interface OrgSpongycastleAsn1X509CRLNumber () {
 @public
  JavaMathBigInteger *number_;
}

@end

J2OBJC_FIELD_SETTER(OrgSpongycastleAsn1X509CRLNumber, number_, JavaMathBigInteger *)

#line 1 "/Users/desarrolloabamobile/Downloads/pades-ios-mini/src/main/java/org/spongycastle/asn1/x509/CRLNumber.java"


#line 15
@implementation OrgSpongycastleAsn1X509CRLNumber


#line 20
- (instancetype)initWithJavaMathBigInteger:(JavaMathBigInteger *)number {
  OrgSpongycastleAsn1X509CRLNumber_initWithJavaMathBigInteger_(self, number);
  return self;
}


#line 26
- (JavaMathBigInteger *)getCRLNumber {
  
#line 28
  return number_;
}


#line 31
- (NSString *)description {
  
#line 33
  return JreStrcat("$@", @"CRLNumber: ", [self getCRLNumber]);
}


#line 36
- (OrgSpongycastleAsn1ASN1Primitive *)toASN1Primitive {
  
#line 38
  return new_OrgSpongycastleAsn1ASN1Integer_initWithJavaMathBigInteger_(number_);
}


#line 41
+ (OrgSpongycastleAsn1X509CRLNumber *)getInstanceWithId:(id)o {
  return OrgSpongycastleAsn1X509CRLNumber_getInstanceWithId_(o);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LJavaMathBigInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgSpongycastleAsn1ASN1Primitive;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgSpongycastleAsn1X509CRLNumber;", 0x9, 2, 3, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithJavaMathBigInteger:);
  methods[1].selector = @selector(getCRLNumber);
  methods[2].selector = @selector(description);
  methods[3].selector = @selector(toASN1Primitive);
  methods[4].selector = @selector(getInstanceWithId:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "number_", "LJavaMathBigInteger;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LJavaMathBigInteger;", "toString", "getInstance", "LNSObject;" };
  static const J2ObjcClassInfo _OrgSpongycastleAsn1X509CRLNumber = { "CRLNumber", "org.spongycastle.asn1.x509", ptrTable, methods, fields, 7, 0x1, 5, 1, -1, -1, -1, -1, -1 };
  return &_OrgSpongycastleAsn1X509CRLNumber;
}

@end


#line 20
void OrgSpongycastleAsn1X509CRLNumber_initWithJavaMathBigInteger_(OrgSpongycastleAsn1X509CRLNumber *self, JavaMathBigInteger *number) {
  OrgSpongycastleAsn1ASN1Object_init(self);
  
#line 23
  self->number_ = number;
}


#line 20
OrgSpongycastleAsn1X509CRLNumber *new_OrgSpongycastleAsn1X509CRLNumber_initWithJavaMathBigInteger_(JavaMathBigInteger *number) {
  J2OBJC_NEW_IMPL(OrgSpongycastleAsn1X509CRLNumber, initWithJavaMathBigInteger_, number)
}


#line 20
OrgSpongycastleAsn1X509CRLNumber *create_OrgSpongycastleAsn1X509CRLNumber_initWithJavaMathBigInteger_(JavaMathBigInteger *number) {
  J2OBJC_CREATE_IMPL(OrgSpongycastleAsn1X509CRLNumber, initWithJavaMathBigInteger_, number)
}


#line 41
OrgSpongycastleAsn1X509CRLNumber *OrgSpongycastleAsn1X509CRLNumber_getInstanceWithId_(id o) {
  OrgSpongycastleAsn1X509CRLNumber_initialize();
  if ([o isKindOfClass:[OrgSpongycastleAsn1X509CRLNumber class]]) {
    
#line 45
    return (OrgSpongycastleAsn1X509CRLNumber *) o;
  }
  else if (o != nil) {
    
#line 49
    return new_OrgSpongycastleAsn1X509CRLNumber_initWithJavaMathBigInteger_([((OrgSpongycastleAsn1ASN1Integer *) nil_chk(OrgSpongycastleAsn1ASN1Integer_getInstanceWithId_(o))) getValue]);
  }
  
#line 52
  return nil;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgSpongycastleAsn1X509CRLNumber)
