//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/pades-ios-mini/src/main/java/org/spongycastle/crypto/params/ECPrivateKeyParameters.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ECPrivateKeyParameters")
#ifdef RESTRICT_ECPrivateKeyParameters
#define INCLUDE_ALL_ECPrivateKeyParameters 0
#else
#define INCLUDE_ALL_ECPrivateKeyParameters 1
#endif
#undef RESTRICT_ECPrivateKeyParameters

#if !defined (OrgSpongycastleCryptoParamsECPrivateKeyParameters_) && (INCLUDE_ALL_ECPrivateKeyParameters || defined(INCLUDE_OrgSpongycastleCryptoParamsECPrivateKeyParameters))
#define OrgSpongycastleCryptoParamsECPrivateKeyParameters_

#define RESTRICT_ECKeyParameters 1
#define INCLUDE_OrgSpongycastleCryptoParamsECKeyParameters 1
#include "ECKeyParameters.h"

@class JavaMathBigInteger;
@class OrgSpongycastleCryptoParamsECDomainParameters;

@interface OrgSpongycastleCryptoParamsECPrivateKeyParameters : OrgSpongycastleCryptoParamsECKeyParameters {
 @public
  JavaMathBigInteger *d_;
}

#pragma mark Public

- (instancetype)initWithJavaMathBigInteger:(JavaMathBigInteger *)d
withOrgSpongycastleCryptoParamsECDomainParameters:(OrgSpongycastleCryptoParamsECDomainParameters *)params;

- (JavaMathBigInteger *)getD;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithBoolean:(jboolean)arg0
withOrgSpongycastleCryptoParamsECDomainParameters:(OrgSpongycastleCryptoParamsECDomainParameters *)arg1 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgSpongycastleCryptoParamsECPrivateKeyParameters)

J2OBJC_FIELD_SETTER(OrgSpongycastleCryptoParamsECPrivateKeyParameters, d_, JavaMathBigInteger *)

FOUNDATION_EXPORT void OrgSpongycastleCryptoParamsECPrivateKeyParameters_initWithJavaMathBigInteger_withOrgSpongycastleCryptoParamsECDomainParameters_(OrgSpongycastleCryptoParamsECPrivateKeyParameters *self, JavaMathBigInteger *d, OrgSpongycastleCryptoParamsECDomainParameters *params);

FOUNDATION_EXPORT OrgSpongycastleCryptoParamsECPrivateKeyParameters *new_OrgSpongycastleCryptoParamsECPrivateKeyParameters_initWithJavaMathBigInteger_withOrgSpongycastleCryptoParamsECDomainParameters_(JavaMathBigInteger *d, OrgSpongycastleCryptoParamsECDomainParameters *params) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgSpongycastleCryptoParamsECPrivateKeyParameters *create_OrgSpongycastleCryptoParamsECPrivateKeyParameters_initWithJavaMathBigInteger_withOrgSpongycastleCryptoParamsECDomainParameters_(JavaMathBigInteger *d, OrgSpongycastleCryptoParamsECDomainParameters *params);

J2OBJC_TYPE_LITERAL_HEADER(OrgSpongycastleCryptoParamsECPrivateKeyParameters)

#endif

#pragma pop_macro("INCLUDE_ALL_ECPrivateKeyParameters")
