//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/pades-ios-mini/src/main/java/org/spongycastle/operator/jcajce/JceGenericKey.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JceGenericKey")
#ifdef RESTRICT_JceGenericKey
#define INCLUDE_ALL_JceGenericKey 0
#else
#define INCLUDE_ALL_JceGenericKey 1
#endif
#undef RESTRICT_JceGenericKey

#if !defined (OrgSpongycastleOperatorJcajceJceGenericKey_) && (INCLUDE_ALL_JceGenericKey || defined(INCLUDE_OrgSpongycastleOperatorJcajceJceGenericKey))
#define OrgSpongycastleOperatorJcajceJceGenericKey_

#define RESTRICT_GenericKey 1
#define INCLUDE_OrgSpongycastleOperatorGenericKey 1
#include "GenericKey.h"

@class IOSByteArray;
@class OrgSpongycastleAsn1X509AlgorithmIdentifier;
@protocol JavaSecurityKey;

@interface OrgSpongycastleOperatorJcajceJceGenericKey : OrgSpongycastleOperatorGenericKey

#pragma mark Public

- (instancetype)initWithOrgSpongycastleAsn1X509AlgorithmIdentifier:(OrgSpongycastleAsn1X509AlgorithmIdentifier *)algorithmIdentifier
                                               withJavaSecurityKey:(id<JavaSecurityKey>)representation;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithId:(id)arg0 NS_UNAVAILABLE;

- (instancetype)initWithOrgSpongycastleAsn1X509AlgorithmIdentifier:(OrgSpongycastleAsn1X509AlgorithmIdentifier *)arg0
                                                     withByteArray:(IOSByteArray *)arg1 NS_UNAVAILABLE;

- (instancetype)initWithOrgSpongycastleAsn1X509AlgorithmIdentifier:(OrgSpongycastleAsn1X509AlgorithmIdentifier *)arg0
                                                            withId:(id)arg1 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgSpongycastleOperatorJcajceJceGenericKey)

FOUNDATION_EXPORT void OrgSpongycastleOperatorJcajceJceGenericKey_initWithOrgSpongycastleAsn1X509AlgorithmIdentifier_withJavaSecurityKey_(OrgSpongycastleOperatorJcajceJceGenericKey *self, OrgSpongycastleAsn1X509AlgorithmIdentifier *algorithmIdentifier, id<JavaSecurityKey> representation);

FOUNDATION_EXPORT OrgSpongycastleOperatorJcajceJceGenericKey *new_OrgSpongycastleOperatorJcajceJceGenericKey_initWithOrgSpongycastleAsn1X509AlgorithmIdentifier_withJavaSecurityKey_(OrgSpongycastleAsn1X509AlgorithmIdentifier *algorithmIdentifier, id<JavaSecurityKey> representation) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgSpongycastleOperatorJcajceJceGenericKey *create_OrgSpongycastleOperatorJcajceJceGenericKey_initWithOrgSpongycastleAsn1X509AlgorithmIdentifier_withJavaSecurityKey_(OrgSpongycastleAsn1X509AlgorithmIdentifier *algorithmIdentifier, id<JavaSecurityKey> representation);

J2OBJC_TYPE_LITERAL_HEADER(OrgSpongycastleOperatorJcajceJceGenericKey)

#endif

#pragma pop_macro("INCLUDE_ALL_JceGenericKey")
