//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/pades-ios-mini/src/main/java/org/spongycastle/math/ec/custom/sec/SecT409K1Curve.java
//

#include "ECCurve.h"
#include "ECFieldElement.h"
#include "ECMultiplier.h"
#include "ECPoint.h"
#include "Hex.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "SecT409FieldElement.h"
#include "SecT409K1Curve.h"
#include "SecT409K1Point.h"
#include "WTauNafMultiplier.h"
#include "java/math/BigInteger.h"

#if !__has_feature(objc_arc)
#error "SecT409K1Curve must be compiled with ARC (-fobjc-arc)"
#endif

inline jint OrgSpongycastleMathEcCustomSecSecT409K1Curve_get_SecT409K1_DEFAULT_COORDS(void);
#define OrgSpongycastleMathEcCustomSecSecT409K1Curve_SecT409K1_DEFAULT_COORDS 6
J2OBJC_STATIC_FIELD_CONSTANT(OrgSpongycastleMathEcCustomSecSecT409K1Curve, SecT409K1_DEFAULT_COORDS, jint)

#line 1 "/Users/desarrolloabamobile/Downloads/pades-ios-mini/src/main/java/org/spongycastle/math/ec/custom/sec/SecT409K1Curve.java"


#line 13
@implementation OrgSpongycastleMathEcCustomSecSecT409K1Curve

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 19
- (instancetype)init {
  OrgSpongycastleMathEcCustomSecSecT409K1Curve_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END


#line 33
- (OrgSpongycastleMathEcECCurve *)cloneCurve {
  
#line 35
  return new_OrgSpongycastleMathEcCustomSecSecT409K1Curve_init();
}


#line 38
- (jboolean)supportsCoordinateSystemWithInt:(jint)coord {
  
#line 40
  switch (coord) {
    
#line 42
    case OrgSpongycastleMathEcECCurve_COORD_LAMBDA_PROJECTIVE:
    return true;
    default:
    return false;
  }
}


#line 49
- (id<OrgSpongycastleMathEcECMultiplier>)createDefaultMultiplier {
  
#line 51
  return new_OrgSpongycastleMathEcWTauNafMultiplier_init();
}


#line 54
- (jint)getFieldSize {
  
#line 56
  return 409;
}


#line 59
- (OrgSpongycastleMathEcECFieldElement *)fromBigIntegerWithJavaMathBigInteger:(JavaMathBigInteger *)x {
  
#line 61
  return new_OrgSpongycastleMathEcCustomSecSecT409FieldElement_initWithJavaMathBigInteger_(x);
}


#line 64
- (OrgSpongycastleMathEcECPoint *)createRawPointWithOrgSpongycastleMathEcECFieldElement:(OrgSpongycastleMathEcECFieldElement *)x
                                                withOrgSpongycastleMathEcECFieldElement:(OrgSpongycastleMathEcECFieldElement *)y
                                                                            withBoolean:(jboolean)withCompression {
  
#line 66
  return new_OrgSpongycastleMathEcCustomSecSecT409K1Point_initWithOrgSpongycastleMathEcECCurve_withOrgSpongycastleMathEcECFieldElement_withOrgSpongycastleMathEcECFieldElement_withBoolean_(self, x, y, withCompression);
}


#line 69
- (OrgSpongycastleMathEcECPoint *)createRawPointWithOrgSpongycastleMathEcECFieldElement:(OrgSpongycastleMathEcECFieldElement *)x
                                                withOrgSpongycastleMathEcECFieldElement:(OrgSpongycastleMathEcECFieldElement *)y
                                           withOrgSpongycastleMathEcECFieldElementArray:(IOSObjectArray *)zs
                                                                            withBoolean:(jboolean)withCompression {
  
#line 71
  return new_OrgSpongycastleMathEcCustomSecSecT409K1Point_initWithOrgSpongycastleMathEcECCurve_withOrgSpongycastleMathEcECFieldElement_withOrgSpongycastleMathEcECFieldElement_withOrgSpongycastleMathEcECFieldElementArray_withBoolean_(self, x, y, zs, withCompression);
}


#line 74
- (OrgSpongycastleMathEcECPoint *)getInfinity {
  
#line 76
  return infinity_;
}


#line 79
- (jboolean)isKoblitz {
  
#line 81
  return true;
}


#line 84
- (jint)getM {
  
#line 86
  return 409;
}


#line 89
- (jboolean)isTrinomial {
  
#line 91
  return true;
}


#line 94
- (jint)getK1 {
  
#line 96
  return 87;
}


#line 99
- (jint)getK2 {
  
#line 101
  return 0;
}


#line 104
- (jint)getK3 {
  
#line 106
  return 0;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgSpongycastleMathEcECCurve;", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "LOrgSpongycastleMathEcECMultiplier;", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgSpongycastleMathEcECFieldElement;", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "LOrgSpongycastleMathEcECPoint;", 0x4, 4, 5, -1, -1, -1, -1 },
    { NULL, "LOrgSpongycastleMathEcECPoint;", 0x4, 4, 6, -1, -1, -1, -1 },
    { NULL, "LOrgSpongycastleMathEcECPoint;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(cloneCurve);
  methods[2].selector = @selector(supportsCoordinateSystemWithInt:);
  methods[3].selector = @selector(createDefaultMultiplier);
  methods[4].selector = @selector(getFieldSize);
  methods[5].selector = @selector(fromBigIntegerWithJavaMathBigInteger:);
  methods[6].selector = @selector(createRawPointWithOrgSpongycastleMathEcECFieldElement:withOrgSpongycastleMathEcECFieldElement:withBoolean:);
  methods[7].selector = @selector(createRawPointWithOrgSpongycastleMathEcECFieldElement:withOrgSpongycastleMathEcECFieldElement:withOrgSpongycastleMathEcECFieldElementArray:withBoolean:);
  methods[8].selector = @selector(getInfinity);
  methods[9].selector = @selector(isKoblitz);
  methods[10].selector = @selector(getM);
  methods[11].selector = @selector(isTrinomial);
  methods[12].selector = @selector(getK1);
  methods[13].selector = @selector(getK2);
  methods[14].selector = @selector(getK3);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "SecT409K1_DEFAULT_COORDS", "I", .constantValue.asInt = OrgSpongycastleMathEcCustomSecSecT409K1Curve_SecT409K1_DEFAULT_COORDS, 0x1a, -1, -1, -1, -1 },
    { "infinity_", "LOrgSpongycastleMathEcCustomSecSecT409K1Point;", .constantValue.asLong = 0, 0x4, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "supportsCoordinateSystem", "I", "fromBigInteger", "LJavaMathBigInteger;", "createRawPoint", "LOrgSpongycastleMathEcECFieldElement;LOrgSpongycastleMathEcECFieldElement;Z", "LOrgSpongycastleMathEcECFieldElement;LOrgSpongycastleMathEcECFieldElement;[LOrgSpongycastleMathEcECFieldElement;Z" };
  static const J2ObjcClassInfo _OrgSpongycastleMathEcCustomSecSecT409K1Curve = { "SecT409K1Curve", "org.spongycastle.math.ec.custom.sec", ptrTable, methods, fields, 7, 0x1, 15, 2, -1, -1, -1, -1, -1 };
  return &_OrgSpongycastleMathEcCustomSecSecT409K1Curve;
}

@end


#line 19
void OrgSpongycastleMathEcCustomSecSecT409K1Curve_init(OrgSpongycastleMathEcCustomSecSecT409K1Curve *self) {
  OrgSpongycastleMathEcECCurve_AbstractF2m_initWithInt_withInt_withInt_withInt_(self,
#line 21
  409, 87, 0, 0);
  
#line 23
  self->infinity_ = new_OrgSpongycastleMathEcCustomSecSecT409K1Point_initWithOrgSpongycastleMathEcECCurve_withOrgSpongycastleMathEcECFieldElement_withOrgSpongycastleMathEcECFieldElement_(self, nil, nil);
  
#line 25
  self->a_ = [self fromBigIntegerWithJavaMathBigInteger:JavaMathBigInteger_valueOfWithLong_(0)];
  self->b_ = [self fromBigIntegerWithJavaMathBigInteger:JavaMathBigInteger_valueOfWithLong_(1)];
  self->order_ = new_JavaMathBigInteger_initWithInt_withByteArray_(1, OrgSpongycastleUtilEncodersHex_decodeWithNSString_(@"7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE5F83B2D4EA20400EC4557D5ED3E3E7CA5B4B5C83B8E01E5FCF"));
  self->cofactor_ = JavaMathBigInteger_valueOfWithLong_(4);
  
#line 30
  self->coord_ = OrgSpongycastleMathEcCustomSecSecT409K1Curve_SecT409K1_DEFAULT_COORDS;
}


#line 19
OrgSpongycastleMathEcCustomSecSecT409K1Curve *new_OrgSpongycastleMathEcCustomSecSecT409K1Curve_init() {
  J2OBJC_NEW_IMPL(OrgSpongycastleMathEcCustomSecSecT409K1Curve, init)
}


#line 19
OrgSpongycastleMathEcCustomSecSecT409K1Curve *create_OrgSpongycastleMathEcCustomSecSecT409K1Curve_init() {
  J2OBJC_CREATE_IMPL(OrgSpongycastleMathEcCustomSecSecT409K1Curve, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgSpongycastleMathEcCustomSecSecT409K1Curve)
