//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/pades-ios-mini/src/main/java/es/gob/afirma/core/misc/SecureXmlBuilder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SecureXmlBuilder")
#ifdef RESTRICT_SecureXmlBuilder
#define INCLUDE_ALL_SecureXmlBuilder 0
#else
#define INCLUDE_ALL_SecureXmlBuilder 1
#endif
#undef RESTRICT_SecureXmlBuilder

#if !defined (EsGobAfirmaCoreMiscSecureXmlBuilder_) && (INCLUDE_ALL_SecureXmlBuilder || defined(INCLUDE_EsGobAfirmaCoreMiscSecureXmlBuilder))
#define EsGobAfirmaCoreMiscSecureXmlBuilder_

@class JavaxXmlParsersDocumentBuilder;
@class JavaxXmlParsersSAXParser;

/*!
 @brief Constructor de objetos para la carga de docuemntos XML.
 */
@interface EsGobAfirmaCoreMiscSecureXmlBuilder : NSObject

#pragma mark Public

- (instancetype)init;

/*!
 @brief Obtiene un generador de &aacute;boles DOM con el que crear o cargar un XML.
 @return Generador de &aacute;rboles DOM.
 @throw ParserConfigurationExceptionCuando ocurre un error durante la creaci&oacute;n.
 */
+ (JavaxXmlParsersDocumentBuilder *)getSecureDocumentBuilder;

/*!
 @brief Construye un parser SAX seguro que no accede a recursos externos.
 @return Factor&iacute;a segura.
 @throw SAXExceptionCuando ocurre un error de SAX.
 @throw ParserConfigurationExceptionCuando no se puede crear el parser.
 */
+ (JavaxXmlParsersSAXParser *)getSecureSAXParser;

@end

J2OBJC_EMPTY_STATIC_INIT(EsGobAfirmaCoreMiscSecureXmlBuilder)

FOUNDATION_EXPORT void EsGobAfirmaCoreMiscSecureXmlBuilder_init(EsGobAfirmaCoreMiscSecureXmlBuilder *self);

FOUNDATION_EXPORT EsGobAfirmaCoreMiscSecureXmlBuilder *new_EsGobAfirmaCoreMiscSecureXmlBuilder_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EsGobAfirmaCoreMiscSecureXmlBuilder *create_EsGobAfirmaCoreMiscSecureXmlBuilder_init(void);

FOUNDATION_EXPORT JavaxXmlParsersDocumentBuilder *EsGobAfirmaCoreMiscSecureXmlBuilder_getSecureDocumentBuilder(void);

FOUNDATION_EXPORT JavaxXmlParsersSAXParser *EsGobAfirmaCoreMiscSecureXmlBuilder_getSecureSAXParser(void);

J2OBJC_TYPE_LITERAL_HEADER(EsGobAfirmaCoreMiscSecureXmlBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_SecureXmlBuilder")
