//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/es/gob/jmulticard/asn1/der/ObjectIdentifier.java
//

#include "IOSClass.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "es/gob/jmulticard/HexUtils.h"
#include "es/gob/jmulticard/asn1/Asn1Exception.h"
#include "es/gob/jmulticard/asn1/DecoderObject.h"
#include "es/gob/jmulticard/asn1/OidDictionary.h"
#include "es/gob/jmulticard/asn1/Tlv.h"
#include "es/gob/jmulticard/asn1/der/ObjectIdentifier.h"
#include "java/lang/IllegalStateException.h"

#if !__has_feature(objc_arc)
#error "es/gob/jmulticard/asn1/der/ObjectIdentifier must be compiled with ARC (-fobjc-arc)"
#endif

@interface EsGobJmulticardAsn1DerObjectIdentifier () {
 @public
  IOSByteArray *rawValue_;
}

@end

J2OBJC_FIELD_SETTER(EsGobJmulticardAsn1DerObjectIdentifier, rawValue_, IOSByteArray *)

inline jbyte EsGobJmulticardAsn1DerObjectIdentifier_get_TAG_OBJECTID(void);
#define EsGobJmulticardAsn1DerObjectIdentifier_TAG_OBJECTID 6
J2OBJC_STATIC_FIELD_CONSTANT(EsGobJmulticardAsn1DerObjectIdentifier, TAG_OBJECTID, jbyte)

inline jbyte EsGobJmulticardAsn1DerObjectIdentifier_get_RELATIVE_OID(void);
#define EsGobJmulticardAsn1DerObjectIdentifier_RELATIVE_OID 13
J2OBJC_STATIC_FIELD_CONSTANT(EsGobJmulticardAsn1DerObjectIdentifier, RELATIVE_OID, jbyte)

#line 1 "/Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/es/gob/jmulticard/asn1/der/ObjectIdentifier.java"


#line 51
@implementation EsGobJmulticardAsn1DerObjectIdentifier

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 51
- (instancetype)init {
  EsGobJmulticardAsn1DerObjectIdentifier_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END


#line 58
- (void)checkTagWithByte:(jbyte)tag {
  
#line 60
  if (EsGobJmulticardAsn1DerObjectIdentifier_TAG_OBJECTID != tag && EsGobJmulticardAsn1DerObjectIdentifier_RELATIVE_OID != tag) {
    @throw new_EsGobJmulticardAsn1Asn1Exception_initWithNSString_(JreStrcat("$$$$$$$$", @"Se esperaba un tipo ", EsGobJmulticardHexUtils_hexifyWithByteArray_withBoolean_([IOSByteArray newArrayWithBytes:(jbyte[]){
#line 62
      EsGobJmulticardAsn1DerObjectIdentifier_TAG_OBJECTID } count:1], false), @" o ", EsGobJmulticardHexUtils_hexifyWithByteArray_withBoolean_([IOSByteArray newArrayWithBytes:(jbyte[]){
#line 63
        EsGobJmulticardAsn1DerObjectIdentifier_RELATIVE_OID } count:1], false), @" (",
#line 64
        [[self java_getClass] getName], @") pero se encontro un tipo ", EsGobJmulticardHexUtils_hexifyWithByteArray_withBoolean_([IOSByteArray newArrayWithBytes:(jbyte[]){
#line 65
          tag } count:1], false)));
        }
      }


#line 70
- (void)decodeValue {
  
#line 72
  rawValue_ = [new_EsGobJmulticardAsn1Tlv_initWithByteArray_([self getBytes]) getValue];
}


#line 75
- (jbyte)getDefaultTag {
  
#line 77
  return EsGobJmulticardAsn1DerObjectIdentifier_TAG_OBJECTID;
}

- (NSString *)description {
  
#line 83
  if (rawValue_ == nil) {
    @throw new_JavaLangIllegalStateException_initWithNSString_(@"El valor del OID no esta establecido");
  }
  return EsGobJmulticardAsn1OidDictionary_getOidDescriptionWithByteArray_(rawValue_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, 2, -1, -1, -1 },
    { NULL, "V", 0x4, -1, -1, 3, -1, -1, -1 },
    { NULL, "B", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 4, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(checkTagWithByte:);
  methods[2].selector = @selector(decodeValue);
  methods[3].selector = @selector(getDefaultTag);
  methods[4].selector = @selector(description);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "TAG_OBJECTID", "B", .constantValue.asChar = EsGobJmulticardAsn1DerObjectIdentifier_TAG_OBJECTID, 0x1a, -1, -1, -1, -1 },
    { "RELATIVE_OID", "B", .constantValue.asChar = EsGobJmulticardAsn1DerObjectIdentifier_RELATIVE_OID, 0x1a, -1, -1, -1, -1 },
    { "rawValue_", "[B", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "checkTag", "B", "LEsGobJmulticardAsn1Asn1Exception;", "LEsGobJmulticardAsn1TlvException;", "toString" };
  static const J2ObjcClassInfo _EsGobJmulticardAsn1DerObjectIdentifier = { "ObjectIdentifier", "es.gob.jmulticard.asn1.der", ptrTable, methods, fields, 7, 0x11, 5, 3, -1, -1, -1, -1, -1 };
  return &_EsGobJmulticardAsn1DerObjectIdentifier;
}

@end


#line 51
void EsGobJmulticardAsn1DerObjectIdentifier_init(EsGobJmulticardAsn1DerObjectIdentifier *self) {
  EsGobJmulticardAsn1DecoderObject_init(self);
  self->rawValue_ =
#line 56
  nil;
}


#line 51
EsGobJmulticardAsn1DerObjectIdentifier *new_EsGobJmulticardAsn1DerObjectIdentifier_init() {
  J2OBJC_NEW_IMPL(EsGobJmulticardAsn1DerObjectIdentifier, init)
}


#line 51
EsGobJmulticardAsn1DerObjectIdentifier *create_EsGobJmulticardAsn1DerObjectIdentifier_init() {
  J2OBJC_CREATE_IMPL(EsGobJmulticardAsn1DerObjectIdentifier, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EsGobJmulticardAsn1DerObjectIdentifier)
