//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/org/spongycastle/math/ec/custom/sec/SecP521R1Field.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/math/BigInteger.h"
#include "org/spongycastle/math/ec/custom/sec/SecP521R1Field.h"
#include "org/spongycastle/math/raw/Nat.h"
#include "org/spongycastle/math/raw/Nat512.h"

#if !__has_feature(objc_arc)
#error "org/spongycastle/math/ec/custom/sec/SecP521R1Field must be compiled with ARC (-fobjc-arc)"
#endif

inline jint OrgSpongycastleMathEcCustomSecSecP521R1Field_get_P16(void);
#define OrgSpongycastleMathEcCustomSecSecP521R1Field_P16 511
J2OBJC_STATIC_FIELD_CONSTANT(OrgSpongycastleMathEcCustomSecSecP521R1Field, P16, jint)

#line 1 "/Users/desarrolloabamobile/Documents/JAVA/pades-ios/src/main/java/org/spongycastle/math/ec/custom/sec/SecP521R1Field.java"

J2OBJC_INITIALIZED_DEFN(OrgSpongycastleMathEcCustomSecSecP521R1Field)

IOSIntArray *OrgSpongycastleMathEcCustomSecSecP521R1Field_P;


#line 8
@implementation OrgSpongycastleMathEcCustomSecSecP521R1Field

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 8
- (instancetype)init {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END


#line 15
+ (void)addWithIntArray:(IOSIntArray *)x
           withIntArray:(IOSIntArray *)y
           withIntArray:(IOSIntArray *)z {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_addWithIntArray_withIntArray_withIntArray_(x, y, z);
}


#line 26
+ (void)addOneWithIntArray:(IOSIntArray *)x
              withIntArray:(IOSIntArray *)z {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_addOneWithIntArray_withIntArray_(x, z);
}


#line 37
+ (IOSIntArray *)fromBigIntegerWithJavaMathBigInteger:(JavaMathBigInteger *)x {
  return OrgSpongycastleMathEcCustomSecSecP521R1Field_fromBigIntegerWithJavaMathBigInteger_(x);
}


#line 47
+ (void)halfWithIntArray:(IOSIntArray *)x
            withIntArray:(IOSIntArray *)z {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_halfWithIntArray_withIntArray_(x, z);
}


#line 54
+ (void)multiplyWithIntArray:(IOSIntArray *)x
                withIntArray:(IOSIntArray *)y
                withIntArray:(IOSIntArray *)z {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_multiplyWithIntArray_withIntArray_withIntArray_(x, y, z);
}


#line 61
+ (void)negateWithIntArray:(IOSIntArray *)x
              withIntArray:(IOSIntArray *)z {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_negateWithIntArray_withIntArray_(x, z);
}


#line 73
+ (void)reduceWithIntArray:(IOSIntArray *)xx
              withIntArray:(IOSIntArray *)z {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_reduceWithIntArray_withIntArray_(xx, z);
}


#line 89
+ (void)reduce23WithIntArray:(IOSIntArray *)z {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_reduce23WithIntArray_(z);
}


#line 101
+ (void)squareWithIntArray:(IOSIntArray *)x
              withIntArray:(IOSIntArray *)z {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_squareWithIntArray_withIntArray_(x, z);
}


#line 108
+ (void)squareNWithIntArray:(IOSIntArray *)x
                    withInt:(jint)n
               withIntArray:(IOSIntArray *)z {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_squareNWithIntArray_withInt_withIntArray_(x, n, z);
}


#line 123
+ (void)subtractWithIntArray:(IOSIntArray *)x
                withIntArray:(IOSIntArray *)y
                withIntArray:(IOSIntArray *)z {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_subtractWithIntArray_withIntArray_withIntArray_(x, y, z);
}


#line 134
+ (void)twiceWithIntArray:(IOSIntArray *)x
             withIntArray:(IOSIntArray *)z {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_twiceWithIntArray_withIntArray_(x, z);
}


#line 141
+ (void)implMultiplyWithIntArray:(IOSIntArray *)x
                    withIntArray:(IOSIntArray *)y
                    withIntArray:(IOSIntArray *)zz {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_implMultiplyWithIntArray_withIntArray_withIntArray_(x, y, zz);
}


#line 149
+ (void)implSquareWithIntArray:(IOSIntArray *)x
                  withIntArray:(IOSIntArray *)zz {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_implSquareWithIntArray_withIntArray_(x, zz);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 2, 3, -1, -1, -1, -1 },
    { NULL, "[I", 0x9, 4, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 6, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 7, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 8, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 9, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 10, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 12, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 13, 14, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 15, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 16, 3, -1, -1, -1, -1 },
    { NULL, "V", 0xc, 17, 1, -1, -1, -1, -1 },
    { NULL, "V", 0xc, 18, 3, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(addWithIntArray:withIntArray:withIntArray:);
  methods[2].selector = @selector(addOneWithIntArray:withIntArray:);
  methods[3].selector = @selector(fromBigIntegerWithJavaMathBigInteger:);
  methods[4].selector = @selector(halfWithIntArray:withIntArray:);
  methods[5].selector = @selector(multiplyWithIntArray:withIntArray:withIntArray:);
  methods[6].selector = @selector(negateWithIntArray:withIntArray:);
  methods[7].selector = @selector(reduceWithIntArray:withIntArray:);
  methods[8].selector = @selector(reduce23WithIntArray:);
  methods[9].selector = @selector(squareWithIntArray:withIntArray:);
  methods[10].selector = @selector(squareNWithIntArray:withInt:withIntArray:);
  methods[11].selector = @selector(subtractWithIntArray:withIntArray:withIntArray:);
  methods[12].selector = @selector(twiceWithIntArray:withIntArray:);
  methods[13].selector = @selector(implMultiplyWithIntArray:withIntArray:withIntArray:);
  methods[14].selector = @selector(implSquareWithIntArray:withIntArray:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "P", "[I", .constantValue.asLong = 0, 0x18, -1, 19, -1, -1 },
    { "P16", "I", .constantValue.asInt = OrgSpongycastleMathEcCustomSecSecP521R1Field_P16, 0x1a, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "add", "[I[I[I", "addOne", "[I[I", "fromBigInteger", "LJavaMathBigInteger;", "half", "multiply", "negate", "reduce", "reduce23", "[I", "square", "squareN", "[II[I", "subtract", "twice", "implMultiply", "implSquare", &OrgSpongycastleMathEcCustomSecSecP521R1Field_P };
  static const J2ObjcClassInfo _OrgSpongycastleMathEcCustomSecSecP521R1Field = { "SecP521R1Field", "org.spongycastle.math.ec.custom.sec", ptrTable, methods, fields, 7, 0x1, 15, 2, -1, -1, -1, -1, -1 };
  return &_OrgSpongycastleMathEcCustomSecSecP521R1Field;
}

+ (void)initialize {
  if (self == [OrgSpongycastleMathEcCustomSecSecP521R1Field class]) {
    OrgSpongycastleMathEcCustomSecSecP521R1Field_P = [IOSIntArray newArrayWithInts:(jint[]){
#line 11
      (jint) 0xFFFFFFFF, (jint) 0xFFFFFFFF, (jint) 0xFFFFFFFF, (jint) 0xFFFFFFFF, (jint) 0xFFFFFFFF, (jint) 0xFFFFFFFF, (jint) 0xFFFFFFFF,
#line 12
      (jint) 0xFFFFFFFF, (jint) 0xFFFFFFFF, (jint) 0xFFFFFFFF, (jint) 0xFFFFFFFF, (jint) 0xFFFFFFFF, (jint) 0xFFFFFFFF, (jint) 0xFFFFFFFF, (jint) 0xFFFFFFFF, (jint) 0xFFFFFFFF, (jint) 0x1FF } count:17];
      J2OBJC_SET_INITIALIZED(OrgSpongycastleMathEcCustomSecSecP521R1Field)
    }
  }

@end


#line 8
void OrgSpongycastleMathEcCustomSecSecP521R1Field_init(OrgSpongycastleMathEcCustomSecSecP521R1Field *self) {
  NSObject_init(self);
}


#line 8
OrgSpongycastleMathEcCustomSecSecP521R1Field *new_OrgSpongycastleMathEcCustomSecSecP521R1Field_init() {
  J2OBJC_NEW_IMPL(OrgSpongycastleMathEcCustomSecSecP521R1Field, init)
}


#line 8
OrgSpongycastleMathEcCustomSecSecP521R1Field *create_OrgSpongycastleMathEcCustomSecSecP521R1Field_init() {
  J2OBJC_CREATE_IMPL(OrgSpongycastleMathEcCustomSecSecP521R1Field, init)
}


#line 15
void OrgSpongycastleMathEcCustomSecSecP521R1Field_addWithIntArray_withIntArray_withIntArray_(IOSIntArray *x, IOSIntArray *y, IOSIntArray *z) {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_initialize();
  jint c = OrgSpongycastleMathRawNat_addWithInt_withIntArray_withIntArray_withIntArray_(16, x, y, z) + IOSIntArray_Get(nil_chk(x), 16) + IOSIntArray_Get(nil_chk(y), 16);
  if (c > OrgSpongycastleMathEcCustomSecSecP521R1Field_P16 || (c == OrgSpongycastleMathEcCustomSecSecP521R1Field_P16 && OrgSpongycastleMathRawNat_eqWithInt_withIntArray_withIntArray_(16, z, OrgSpongycastleMathEcCustomSecSecP521R1Field_P))) {
    
#line 20
    c += OrgSpongycastleMathRawNat_incWithInt_withIntArray_(16, z);
    c &= OrgSpongycastleMathEcCustomSecSecP521R1Field_P16;
  }
  *IOSIntArray_GetRef(nil_chk(z), 16) = c;
}


#line 26
void OrgSpongycastleMathEcCustomSecSecP521R1Field_addOneWithIntArray_withIntArray_(IOSIntArray *x, IOSIntArray *z) {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_initialize();
  jint c = OrgSpongycastleMathRawNat_incWithInt_withIntArray_withIntArray_(16, x, z) + IOSIntArray_Get(nil_chk(x), 16);
  if (c > OrgSpongycastleMathEcCustomSecSecP521R1Field_P16 || (c == OrgSpongycastleMathEcCustomSecSecP521R1Field_P16 && OrgSpongycastleMathRawNat_eqWithInt_withIntArray_withIntArray_(16, z, OrgSpongycastleMathEcCustomSecSecP521R1Field_P))) {
    
#line 31
    c += OrgSpongycastleMathRawNat_incWithInt_withIntArray_(16, z);
    c &= OrgSpongycastleMathEcCustomSecSecP521R1Field_P16;
  }
  *IOSIntArray_GetRef(nil_chk(z), 16) = c;
}


#line 37
IOSIntArray *OrgSpongycastleMathEcCustomSecSecP521R1Field_fromBigIntegerWithJavaMathBigInteger_(JavaMathBigInteger *x) {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_initialize();
  IOSIntArray *z = OrgSpongycastleMathRawNat_fromBigIntegerWithInt_withJavaMathBigInteger_(521, x);
  if (OrgSpongycastleMathRawNat_eqWithInt_withIntArray_withIntArray_(17, z, OrgSpongycastleMathEcCustomSecSecP521R1Field_P)) {
    
#line 42
    OrgSpongycastleMathRawNat_zeroWithInt_withIntArray_(17, z);
  }
  return z;
}


#line 47
void OrgSpongycastleMathEcCustomSecSecP521R1Field_halfWithIntArray_withIntArray_(IOSIntArray *x, IOSIntArray *z) {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_initialize();
  jint x16 = IOSIntArray_Get(nil_chk(x), 16);
  jint c = OrgSpongycastleMathRawNat_shiftDownBitWithInt_withIntArray_withInt_withIntArray_(16, x, x16, z);
  *IOSIntArray_GetRef(nil_chk(z), 16) = (JreURShift32(x16, 1)) | (JreURShift32(c, 23));
}

void OrgSpongycastleMathEcCustomSecSecP521R1Field_multiplyWithIntArray_withIntArray_withIntArray_(IOSIntArray *x, IOSIntArray *y, IOSIntArray *z) {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_initialize();
  IOSIntArray *tt = OrgSpongycastleMathRawNat_createWithInt_(33);
  OrgSpongycastleMathEcCustomSecSecP521R1Field_implMultiplyWithIntArray_withIntArray_withIntArray_(x, y, tt);
  OrgSpongycastleMathEcCustomSecSecP521R1Field_reduceWithIntArray_withIntArray_(tt, z);
}

void OrgSpongycastleMathEcCustomSecSecP521R1Field_negateWithIntArray_withIntArray_(IOSIntArray *x, IOSIntArray *z) {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_initialize();
  if (OrgSpongycastleMathRawNat_isZeroWithInt_withIntArray_(17, x)) {
    
#line 65
    OrgSpongycastleMathRawNat_zeroWithInt_withIntArray_(17, z);
  }
  else {
    
#line 69
    OrgSpongycastleMathRawNat_subWithInt_withIntArray_withIntArray_withIntArray_(17, OrgSpongycastleMathEcCustomSecSecP521R1Field_P, x, z);
  }
}


#line 73
void OrgSpongycastleMathEcCustomSecSecP521R1Field_reduceWithIntArray_withIntArray_(IOSIntArray *xx, IOSIntArray *z) {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_initialize();
  
#line 77
  jint xx32 = IOSIntArray_Get(nil_chk(xx), 32);
  jint c = JreURShift32(OrgSpongycastleMathRawNat_shiftDownBitsWithInt_withIntArray_withInt_withInt_withInt_withIntArray_withInt_(16, xx, 16, 9, xx32, z, 0), 23);
  c += JreURShift32(xx32, 9);
  c += OrgSpongycastleMathRawNat_addToWithInt_withIntArray_withIntArray_(16, xx, z);
  if (c > OrgSpongycastleMathEcCustomSecSecP521R1Field_P16 || (c == OrgSpongycastleMathEcCustomSecSecP521R1Field_P16 && OrgSpongycastleMathRawNat_eqWithInt_withIntArray_withIntArray_(16, z, OrgSpongycastleMathEcCustomSecSecP521R1Field_P))) {
    
#line 83
    c += OrgSpongycastleMathRawNat_incWithInt_withIntArray_(16, z);
    c &= OrgSpongycastleMathEcCustomSecSecP521R1Field_P16;
  }
  *IOSIntArray_GetRef(nil_chk(z), 16) = c;
}


#line 89
void OrgSpongycastleMathEcCustomSecSecP521R1Field_reduce23WithIntArray_(IOSIntArray *z) {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_initialize();
  jint z16 = IOSIntArray_Get(nil_chk(z), 16);
  jint c = OrgSpongycastleMathRawNat_addWordToWithInt_withInt_withIntArray_(16, JreURShift32(z16, 9), z) + (z16 & OrgSpongycastleMathEcCustomSecSecP521R1Field_P16);
  if (c > OrgSpongycastleMathEcCustomSecSecP521R1Field_P16 || (c == OrgSpongycastleMathEcCustomSecSecP521R1Field_P16 && OrgSpongycastleMathRawNat_eqWithInt_withIntArray_withIntArray_(16, z, OrgSpongycastleMathEcCustomSecSecP521R1Field_P))) {
    
#line 95
    c += OrgSpongycastleMathRawNat_incWithInt_withIntArray_(16, z);
    c &= OrgSpongycastleMathEcCustomSecSecP521R1Field_P16;
  }
  *IOSIntArray_GetRef(z, 16) = c;
}


#line 101
void OrgSpongycastleMathEcCustomSecSecP521R1Field_squareWithIntArray_withIntArray_(IOSIntArray *x, IOSIntArray *z) {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_initialize();
  IOSIntArray *tt = OrgSpongycastleMathRawNat_createWithInt_(33);
  OrgSpongycastleMathEcCustomSecSecP521R1Field_implSquareWithIntArray_withIntArray_(x, tt);
  OrgSpongycastleMathEcCustomSecSecP521R1Field_reduceWithIntArray_withIntArray_(tt, z);
}

void OrgSpongycastleMathEcCustomSecSecP521R1Field_squareNWithIntArray_withInt_withIntArray_(IOSIntArray *x, jint n, IOSIntArray *z) {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_initialize();
  
#line 112
  IOSIntArray *tt = OrgSpongycastleMathRawNat_createWithInt_(33);
  OrgSpongycastleMathEcCustomSecSecP521R1Field_implSquareWithIntArray_withIntArray_(x, tt);
  OrgSpongycastleMathEcCustomSecSecP521R1Field_reduceWithIntArray_withIntArray_(tt, z);
  
#line 116
  while (--n > 0) {
    
#line 118
    OrgSpongycastleMathEcCustomSecSecP521R1Field_implSquareWithIntArray_withIntArray_(z, tt);
    OrgSpongycastleMathEcCustomSecSecP521R1Field_reduceWithIntArray_withIntArray_(tt, z);
  }
}


#line 123
void OrgSpongycastleMathEcCustomSecSecP521R1Field_subtractWithIntArray_withIntArray_withIntArray_(IOSIntArray *x, IOSIntArray *y, IOSIntArray *z) {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_initialize();
  jint c = OrgSpongycastleMathRawNat_subWithInt_withIntArray_withIntArray_withIntArray_(16, x, y, z) + IOSIntArray_Get(nil_chk(x), 16) - IOSIntArray_Get(nil_chk(y), 16);
  if (c < 0) {
    
#line 128
    c += OrgSpongycastleMathRawNat_decWithInt_withIntArray_(16, z);
    c &= OrgSpongycastleMathEcCustomSecSecP521R1Field_P16;
  }
  *IOSIntArray_GetRef(nil_chk(z), 16) = c;
}


#line 134
void OrgSpongycastleMathEcCustomSecSecP521R1Field_twiceWithIntArray_withIntArray_(IOSIntArray *x, IOSIntArray *z) {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_initialize();
  jint x16 = IOSIntArray_Get(nil_chk(x), 16);
  jint c = OrgSpongycastleMathRawNat_shiftUpBitWithInt_withIntArray_withInt_withIntArray_(16, x, JreLShift32(x16, 23), z) | (JreLShift32(x16, 1));
  *IOSIntArray_GetRef(nil_chk(z), 16) = c & OrgSpongycastleMathEcCustomSecSecP521R1Field_P16;
}

void OrgSpongycastleMathEcCustomSecSecP521R1Field_implMultiplyWithIntArray_withIntArray_withIntArray_(IOSIntArray *x, IOSIntArray *y, IOSIntArray *zz) {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_initialize();
  OrgSpongycastleMathRawNat512_mulWithIntArray_withIntArray_withIntArray_(x, y, zz);
  
#line 145
  jint x16 = IOSIntArray_Get(nil_chk(x), 16);
  
#line 145
  jint y16 = IOSIntArray_Get(nil_chk(y), 16);
  *IOSIntArray_GetRef(nil_chk(zz), 32) = OrgSpongycastleMathRawNat_mul31BothAddWithInt_withInt_withIntArray_withInt_withIntArray_withIntArray_withInt_(16, x16, y, y16, x, zz, 16) + (x16 * y16);
}


#line 149
void OrgSpongycastleMathEcCustomSecSecP521R1Field_implSquareWithIntArray_withIntArray_(IOSIntArray *x, IOSIntArray *zz) {
  OrgSpongycastleMathEcCustomSecSecP521R1Field_initialize();
  OrgSpongycastleMathRawNat512_squareWithIntArray_withIntArray_(x, zz);
  
#line 153
  jint x16 = IOSIntArray_Get(nil_chk(x), 16);
  *IOSIntArray_GetRef(nil_chk(zz), 32) = OrgSpongycastleMathRawNat_mulWordAddToWithInt_withInt_withIntArray_withInt_withIntArray_withInt_(16, JreLShift32(x16, 1), x, 0, zz, 16) + (x16 * x16);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgSpongycastleMathEcCustomSecSecP521R1Field)
