//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/org/bouncycastle/asn1/x509/AttCertIssuer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgBouncycastleAsn1X509AttCertIssuer")
#ifdef RESTRICT_OrgBouncycastleAsn1X509AttCertIssuer
#define INCLUDE_ALL_OrgBouncycastleAsn1X509AttCertIssuer 0
#else
#define INCLUDE_ALL_OrgBouncycastleAsn1X509AttCertIssuer 1
#endif
#undef RESTRICT_OrgBouncycastleAsn1X509AttCertIssuer

#if !defined (OrgBouncycastleAsn1X509AttCertIssuer_) && (INCLUDE_ALL_OrgBouncycastleAsn1X509AttCertIssuer || defined(INCLUDE_OrgBouncycastleAsn1X509AttCertIssuer))
#define OrgBouncycastleAsn1X509AttCertIssuer_

#define RESTRICT_OrgBouncycastleAsn1ASN1Object 1
#define INCLUDE_OrgBouncycastleAsn1ASN1Object 1
#include "org/bouncycastle/asn1/ASN1Object.h"

#define RESTRICT_OrgBouncycastleAsn1ASN1Choice 1
#define INCLUDE_OrgBouncycastleAsn1ASN1Choice 1
#include "org/bouncycastle/asn1/ASN1Choice.h"

@class OrgBouncycastleAsn1ASN1Primitive;
@class OrgBouncycastleAsn1ASN1TaggedObject;
@class OrgBouncycastleAsn1X509GeneralNames;
@class OrgBouncycastleAsn1X509V2Form;
@protocol OrgBouncycastleAsn1ASN1Encodable;

@interface OrgBouncycastleAsn1X509AttCertIssuer : OrgBouncycastleAsn1ASN1Object < OrgBouncycastleAsn1ASN1Choice > {
 @public
  id<OrgBouncycastleAsn1ASN1Encodable> obj_;
  OrgBouncycastleAsn1ASN1Primitive *choiceObj_;
}

#pragma mark Public

/*!
 @brief Don't use this one if you are trying to be RFC 3281 compliant.
 Use it for v1 attribute certificates only.
 @param names our GeneralNames structure
 */
- (instancetype)initWithOrgBouncycastleAsn1X509GeneralNames:(OrgBouncycastleAsn1X509GeneralNames *)names;

- (instancetype)initWithOrgBouncycastleAsn1X509V2Form:(OrgBouncycastleAsn1X509V2Form *)v2Form;

+ (OrgBouncycastleAsn1X509AttCertIssuer *)getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject:(OrgBouncycastleAsn1ASN1TaggedObject *)obj
                                                                                 withBoolean:(jboolean)explicit_;

+ (OrgBouncycastleAsn1X509AttCertIssuer *)getInstanceWithId:(id)obj;

- (id<OrgBouncycastleAsn1ASN1Encodable>)getIssuer;

/*!
 @brief Produce an object suitable for an ASN1OutputStream.
 @code

   AttCertIssuer ::= CHOICE {
        v1Form   GeneralNames,  -- MUST NOT be used in this
                                -- profile
        v2Form   [0] V2Form     -- v2 only
   } 
  
@endcode
 */
- (OrgBouncycastleAsn1ASN1Primitive *)toASN1Primitive;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleAsn1X509AttCertIssuer)

J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1X509AttCertIssuer, obj_, id<OrgBouncycastleAsn1ASN1Encodable>)
J2OBJC_FIELD_SETTER(OrgBouncycastleAsn1X509AttCertIssuer, choiceObj_, OrgBouncycastleAsn1ASN1Primitive *)

FOUNDATION_EXPORT OrgBouncycastleAsn1X509AttCertIssuer *OrgBouncycastleAsn1X509AttCertIssuer_getInstanceWithId_(id obj);

FOUNDATION_EXPORT OrgBouncycastleAsn1X509AttCertIssuer *OrgBouncycastleAsn1X509AttCertIssuer_getInstanceWithOrgBouncycastleAsn1ASN1TaggedObject_withBoolean_(OrgBouncycastleAsn1ASN1TaggedObject *obj, jboolean explicit_);

FOUNDATION_EXPORT void OrgBouncycastleAsn1X509AttCertIssuer_initWithOrgBouncycastleAsn1X509GeneralNames_(OrgBouncycastleAsn1X509AttCertIssuer *self, OrgBouncycastleAsn1X509GeneralNames *names);

FOUNDATION_EXPORT OrgBouncycastleAsn1X509AttCertIssuer *new_OrgBouncycastleAsn1X509AttCertIssuer_initWithOrgBouncycastleAsn1X509GeneralNames_(OrgBouncycastleAsn1X509GeneralNames *names) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgBouncycastleAsn1X509AttCertIssuer *create_OrgBouncycastleAsn1X509AttCertIssuer_initWithOrgBouncycastleAsn1X509GeneralNames_(OrgBouncycastleAsn1X509GeneralNames *names);

FOUNDATION_EXPORT void OrgBouncycastleAsn1X509AttCertIssuer_initWithOrgBouncycastleAsn1X509V2Form_(OrgBouncycastleAsn1X509AttCertIssuer *self, OrgBouncycastleAsn1X509V2Form *v2Form);

FOUNDATION_EXPORT OrgBouncycastleAsn1X509AttCertIssuer *new_OrgBouncycastleAsn1X509AttCertIssuer_initWithOrgBouncycastleAsn1X509V2Form_(OrgBouncycastleAsn1X509V2Form *v2Form) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgBouncycastleAsn1X509AttCertIssuer *create_OrgBouncycastleAsn1X509AttCertIssuer_initWithOrgBouncycastleAsn1X509V2Form_(OrgBouncycastleAsn1X509V2Form *v2Form);

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleAsn1X509AttCertIssuer)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgBouncycastleAsn1X509AttCertIssuer")
