//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/org/bouncycastle/jcajce/io/SignatureUpdatingOutputStream.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgBouncycastleJcajceIoSignatureUpdatingOutputStream")
#ifdef RESTRICT_OrgBouncycastleJcajceIoSignatureUpdatingOutputStream
#define INCLUDE_ALL_OrgBouncycastleJcajceIoSignatureUpdatingOutputStream 0
#else
#define INCLUDE_ALL_OrgBouncycastleJcajceIoSignatureUpdatingOutputStream 1
#endif
#undef RESTRICT_OrgBouncycastleJcajceIoSignatureUpdatingOutputStream

#if !defined (OrgBouncycastleJcajceIoSignatureUpdatingOutputStream_) && (INCLUDE_ALL_OrgBouncycastleJcajceIoSignatureUpdatingOutputStream || defined(INCLUDE_OrgBouncycastleJcajceIoSignatureUpdatingOutputStream))
#define OrgBouncycastleJcajceIoSignatureUpdatingOutputStream_

#define RESTRICT_JavaIoOutputStream 1
#define INCLUDE_JavaIoOutputStream 1
#include "java/io/OutputStream.h"

@class IOSByteArray;
@class JavaSecuritySignature;

@interface OrgBouncycastleJcajceIoSignatureUpdatingOutputStream : JavaIoOutputStream

#pragma mark Public

- (void)writeWithByteArray:(IOSByteArray *)bytes;

- (void)writeWithByteArray:(IOSByteArray *)bytes
                   withInt:(jint)off
                   withInt:(jint)len;

- (void)writeWithInt:(jint)b;

#pragma mark Package-Private

- (instancetype)initPackagePrivateWithJavaSecuritySignature:(JavaSecuritySignature *)sig;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleJcajceIoSignatureUpdatingOutputStream)

FOUNDATION_EXPORT void OrgBouncycastleJcajceIoSignatureUpdatingOutputStream_initPackagePrivateWithJavaSecuritySignature_(OrgBouncycastleJcajceIoSignatureUpdatingOutputStream *self, JavaSecuritySignature *sig);

FOUNDATION_EXPORT OrgBouncycastleJcajceIoSignatureUpdatingOutputStream *new_OrgBouncycastleJcajceIoSignatureUpdatingOutputStream_initPackagePrivateWithJavaSecuritySignature_(JavaSecuritySignature *sig) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgBouncycastleJcajceIoSignatureUpdatingOutputStream *create_OrgBouncycastleJcajceIoSignatureUpdatingOutputStream_initPackagePrivateWithJavaSecuritySignature_(JavaSecuritySignature *sig);

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleJcajceIoSignatureUpdatingOutputStream)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgBouncycastleJcajceIoSignatureUpdatingOutputStream")
